### ISSUE TITLE
Win32 MidiInDummy: This class provides no functionality.

### ISSUE THREAD

**Issue by Hanleon** [thestk/rtmidi#103]
Hi, 
I used new version 2.1.1 Rtmidi library, and Win32 project, and VS2012.
The code is very sample like this:
```
#include<windows.h>
#include <MMSystem.h>
#include "RtMidi.h" 

int main()
{
  RtMidiIn *midiin = 0;
  // RtMidiIn constructor
  try {
    midiin = new RtMidiIn();
  }
  catch (RtMidiError &error) {
    // Handle the exception here
    error.printMessage();
  }
  // Clean up
  delete midiin;

  system("pause");
}
```

But it will show the error about "MidiInDummy: This class provides no functionality.".
How can I fix this problem?
Thanks a lot~

**Comment by SpotlightKid** [comment]
How did you compile RtMidi / you program? You need to define `__WINDOWS_MM__` and configure your compiler/linker to include the windows multimedia library. See the compiler section at  http://www.music.mcgill.ca/~gary/rtmidi/.

**Comment by Hanleon** [comment]
I forgot define `__WINDOWS_MM__` and add `odbc32.lib odbccp32.lib winmm.lib`  in setting. Now, I fixed it, thank your so much. 👍
