### ISSUE TITLE
C wrapper seems to be leaking the proxy callback userdata

### ISSUE THREAD

**Issue by zserge** [thestk/rtmidi#104]
In the C wrapper a new proxy userdata object is allocated and I don't think it's ever deleted:

https://github.com/thestk/rtmidi/blob/master/rtmidi_c.cpp#L187

I might be wrong though.

**Comment by radarsat1** [comment]
Looks like it.

**Comment by radarsat1** [comment]
@zserge  Can you test?

**Comment by zserge** [comment]
@radarsat1 Yes, all looks good, thanks!

**Comment by radarsat1** [comment]
Excellent :)
