### ISSUE TITLE
RtMidi is not able to see PureData

### ISSUE THREAD

**Issue by jcelerier** [thestk/rtmidi#107]
In the software I work on I couldn't see Pd's virtual ports (Linux ALSA). So I tested with the Python [mido](http://mido.readthedocs.io/en/latest/backends/index.html) library which is a wrapper over RtMidi and PortMidi, and it does not see them either. However, mido with the PortMidi backend is able to see the Pd ports.

```
import rtmidi
import mido

portmidi = mido.Backend('mido.backends.portmidi')
rtmidi = mido.Backend('mido.backends.rtmidi')

rtmidi.get_input_names()
> ['KMidimon:KMidimon 128:0', 'Midi Through:Midi Through Port-0 14:0']

portmidi.get_input_names()
> ['KMidimon', 'Midi Through Port-0', 'Pure Data Midi-Out 1', 'Pure Data Midi-Out 2']
```

**Comment by radarsat1** [comment]
It seems worth noting that PureData users PortMidi as well, so it's not super surprising that the portmidi backend is compatible.  Also, from a glance at RtMidi.cpp, it appears there are two separate functions for normal ports (MidiInAlsa::openPort) and virtual ports (MidiInAlsa::openVirtualPort), so I assume that has something to do with it.

When running PureData on my Ubuntu laptop, with 2 open virtual midi ports, here is some output of relevant commands:

rtmidi's midiproble,
~~~
$ ./midiprobe 

Compiled APIs:
  Linux ALSA

Current input API: Linux ALSA

There are 1 MIDI input sources available.
  Input Port #1: Midi Through 14:0

Current output API: Linux ALSA

There are 1 MIDI output ports available.
  Output Port #1: Midi Through 14:0
~~~

alsa midi utility,
~~~
$ amidi -l
Dir Device    Name
~~~

aconnect,
~~~
$ aconnect -l
client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 128: 'Pure Data' [type=user]
    0 'Pure Data Midi-In 1'
    1 'Pure Data Midi-In 2'
    2 'Pure Data Midi-Out 1'
    3 'Pure Data Midi-Out 2'
~~~

So, it would appear that RtMidi is not showing the "type=user" ports.

**Comment by radarsat1** [comment]
The function used to get port information is called portInfo() in RtMidi.cpp.  (It should really be `static`..)

Anyways it contains a predicate that causes it specifically to skip "synth" ports,
~~~
      if ( ( ( atyp & SND_SEQ_PORT_TYPE_MIDI_GENERIC ) == 0 ) &&                         
        ( ( atyp & SND_SEQ_PORT_TYPE_SYNTH ) == 0 ) ) continue;   
~~~

If I comment this out, I get the following output from midiprobe,

~~~
$ ./midiprobe 

Compiled APIs:
  Linux ALSA

Current input API: Linux ALSA

There are 3 MIDI input sources available.
  Input Port #1: Midi Through 14:0
  Input Port #2: Pure Data 128:2
  Input Port #3: Pure Data 128:3

Current output API: Linux ALSA

There are 3 MIDI output ports available.
  Output Port #1: Midi Through 14:0
  Output Port #2: Pure Data 128:0
  Output Port #3: Pure Data 128:1
~~~

I am not entirely sure what the motivation for this filtering predicate is, so I hesitate to change it.  Perhaps @garyscavone can comment?  I think the idea actually is to specifically restrict the list to hardware ports, but I am not sure why.

**Comment by jcelerier** [comment]
this was apparently added in this commit: https://github.com/thestk/rtmidi/commit/28321c051ed849b0fbd1f7b1aaee19b8ca807390

**Comment by jcelerier** [comment]
Apparently, the flag means: 

> This port understands SND_SEQ_EVENT_SAMPLE_xxx messages (these are not MIDI messages)

but AFAIK you can send midi messages to Pd.

**Comment by jcelerier** [comment]
Sorry, this was dumb: just removing the second flag does not change anything. Removing the whole check however seems to work for me.

**Comment by jcelerier** [comment]
When printing all flags, it seems that the only flag set for puredata is : 

SND_SEQ_PORT_TYPE_APPLICATION

**Comment by jcelerier** [comment]
Interestingly, portmidi seems to set both APPLICATION and GENERIC: 

https://github.com/pure-data/pure-data/blob/master/portmidi/portmidi/pm_linux/pmlinuxalsa.c#L143

**Comment by garyscavone** [comment]
I think that code snippet was intended to filter out all MIDI port types other than GENERIC and SYNTHs (rather than skip “synth” ports). But the documentation for ALSA has always been a bit limited and perhaps the library behaviour has changed over time too. So, perhaps someone can explore what the most appropriate flags should be and submit a pr.

**Comment by jcelerier** [comment]
@garyscavone : https://github.com/thestk/rtmidi/pull/108 . Thanks !
