### ISSUE TITLE
Submit your license to Open Source Initiative and get it approved as OSS

### ISSUE THREAD

**Issue by ericfont** [thestk/rtmidi#110]
Your license is a custom MIT that has a "non-binding" request to submit modifications to developer. 
 While this sounds reasonable and simple, and while I agree with the spirit of the license, unfortunately there is a problem of "License Proliferation" https://opensource.org/proliferation-report resulting in a situation where there are so many licenses and so much confusion that organizations may be wary about using non-trusted licenses (they might have a policy of not including any license not officially approved, for instance), especially if going to incorporate into a commercial product.

I would suggest you submit your custom license to https://opensource.org/approval.  Or change the license text to MIT, and move your request out of the actual license text and leave it in the README.md just above the disclaimer.  Since the request is not legally-binding, it shouldn't really belong in the license text anyway.

**Comment by radarsat1** [comment]
As much as I abhor this kind of drive-by github issues, I do think that we may as well use the standard MIT license text. @garyscavone what do you think?

**Comment by garyscavone** [comment]
RtMidi, RtAudio and STK all have the same license text. It's been that way for at least 15 years or so. I'm not interested in changing it.
