### ISSUE TITLE
Problem with installation during pip install --user python-rtmidi

### ISSUE THREAD

**Issue by shyamalschandra** [thestk/rtmidi#111]
I am getting the following error in Ubuntu 17.04 when trying to install python-rtmidi from pip:
```
shyamal@shyamal-Inspiron-7548:~$ pip install --user python-rtmidi
Collecting python-rtmidi
  Using cached python-rtmidi-1.1.0.zip
Building wheels for collected packages: python-rtmidi
  Running setup.py bdist_wheel for python-rtmidi ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xCv92E/python-rtmidi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpe04Ofbpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/rtmidi
  copying rtmidi/midiutil.py -> build/lib.linux-x86_64-2.7/rtmidi
  copying rtmidi/__init__.py -> build/lib.linux-x86_64-2.7/rtmidi
  copying rtmidi/midiconstants.py -> build/lib.linux-x86_64-2.7/rtmidi
  copying rtmidi/release.py -> build/lib.linux-x86_64-2.7/rtmidi
  running build_ext
  building 'rtmidi._rtmidi' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/usr/include/python2.7 -c src/_rtmidi.cpp -o build/temp.linux-x86_64-2.7/src/_rtmidi.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  src/_rtmidi.cpp: In function ‘void init_rtmidi()’:
  src/_rtmidi.cpp:6955:32: warning: self-comparison always evaluates to true [-Wtautological-compare]
     __pyx_t_2 = ((&PyBytes_Type) == (&PyString_Type));
                  ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/usr/include/python2.7 -c src/RtMidi.cpp -o build/temp.linux-x86_64-2.7/src/RtMidi.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  src/RtMidi.cpp:2448:23: fatal error: jack/jack.h: No such file or directory
   #include <jack/jack.h>
                         ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for python-rtmidi
  Running setup.py clean for python-rtmidi
Failed to build python-rtmidi
Installing collected packages: python-rtmidi
  Running setup.py install for python-rtmidi ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xCv92E/python-rtmidi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8NJ8ff-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/rtmidi
    copying rtmidi/midiutil.py -> build/lib.linux-x86_64-2.7/rtmidi
    copying rtmidi/__init__.py -> build/lib.linux-x86_64-2.7/rtmidi
    copying rtmidi/midiconstants.py -> build/lib.linux-x86_64-2.7/rtmidi
    copying rtmidi/release.py -> build/lib.linux-x86_64-2.7/rtmidi
    running build_ext
    building 'rtmidi._rtmidi' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/usr/include/python2.7 -c src/_rtmidi.cpp -o build/temp.linux-x86_64-2.7/src/_rtmidi.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    src/_rtmidi.cpp: In function ‘void init_rtmidi()’:
    src/_rtmidi.cpp:6955:32: warning: self-comparison always evaluates to true [-Wtautological-compare]
       __pyx_t_2 = ((&PyBytes_Type) == (&PyString_Type));
                    ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc -I/usr/include/python2.7 -c src/RtMidi.cpp -o build/temp.linux-x86_64-2.7/src/RtMidi.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    src/RtMidi.cpp:2448:23: fatal error: jack/jack.h: No such file or directory
     #include <jack/jack.h>
                           ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-xCv92E/python-rtmidi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8NJ8ff-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-xCv92E/python-rtmidi/

```

**Comment by radarsat1** [comment]
I was going to suggest you file this issue over on the rtmidi-python project.  https://github.com/superquadratic/rtmidi-python, but actually this is an easy one, you simply don't have Jack installed.  I don't know what operating system you are using but you probably need to install Jack headers, e.g. `apt-get install libjack-dev`.  Although I'm not 100% sure why it's choosing Jack as the MIDI back-end, but you'll have to ask over on the relevant project.

**Comment by SpotlightKid** [comment]
Hi, author of [python-rtmidi](https://github.com/SpotlightKid/python-rtmidi) here. Sorry for the late feedback, I was on holiday the last two weeks.

Firstly, `python-rtmidi` is not the same package as `rtmidi-python`. I'm not associated with the latter package, but anyway, @shyamalschandra was trying to install the former (my package).

Secondly, @shyamalschandra, please make sure that you have all the requirements installed, as documented [here](https://spotlightkid.github.io/python-rtmidi/installation.html#requirements). I think you're just missing the `libjack-dev` package.

**Comment by garyscavone** [comment]
Issue not applicable.

**Comment by franciscoprado** [comment]
I use Linux Mint 19.1, and I had troubles to install `python-rtmidi` using pip. I solved it by installing the packages `libasound2-dev` and `libjack-dev` (or `libjack-jackd2-dev`), as informed in this section: https://spotlightkid.github.io/python-rtmidi/installation.html#linux

**Comment by lattennn** [comment]
> Hi, author of [python-rtmidi](https://github.com/SpotlightKid/python-rtmidi) here. Sorry for the late feedback, I was on holiday the last two weeks.
> 
> Firstly, `python-rtmidi` is not the same package as `rtmidi-python`. I'm not associated with the latter package, but anyway, @shyamalschandra was trying to install the former (my package).
> 
> Secondly, @shyamalschandra, please make sure that you have all the requirements installed, as documented [here](https://spotlightkid.github.io/python-rtmidi/installation.html#requirements). I think you're just missing the `libjack-dev` package.

Hi, dear author. I got the same problem and I tried to download libasound2-dev and libjack-dev (or libjack-jackd2-dev), as informed in this section: https://spotlightkid.github.io/python-rtmidi/installation.html#linux But I still have not solve it!!!! I am using the ubuntu 16.04 system in the VMworkstation and python 3.6. I have download the pip and it works for all other packets. Could you please help me and tell me what would be the problem?

**Comment by SpotlightKid** [comment]
@shyamalschandra Please open an issue at https://github.com/SpotlightKid/python-rtmidi/issues and paste the full command you are using when trying to install python-rtmidi and its full output. Also show the output of `dpkg-query -s libasound2-dev` and `dpkg-query -s libjack-jackd2-dev`.

**Comment by lattennn** [comment]
> @shyamalschandra Please open an issue at https://github.com/SpotlightKid/python-rtmidi/issues and paste the full command you are using when trying to install python-rtmidi and its full output. Also show the output of `dpkg-query -s libasound2-dev` and `dpkg-query -s libjack-jackd2-dev`.

Dear Author, this is all the error outputs:

#############################################

(tesi) lattennn@ubuntu:~/Thesis/antonio$ pip3 install python-rtmidi
Collecting python-rtmidi
  Downloading python-rtmidi-1.4.6.tar.gz (247 kB)
     |████████████████████████████████| 247 kB 1.2 MB/s 
Building wheels for collected packages: python-rtmidi
  Building wheel for python-rtmidi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/lattennn/tesi/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-le3r8rvf
       cwd: /tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/
  Complete output (35 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/__init__.py -> build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/version.py -> build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/midiconstants.py -> build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/midiutil.py -> build/lib.linux-x86_64-3.6/rtmidi
  running egg_info
  writing python_rtmidi.egg-info/PKG-INFO
  writing dependency_links to python_rtmidi.egg-info/dependency_links.txt
  writing top-level names to python_rtmidi.egg-info/top_level.txt
  reading manifest file 'python_rtmidi.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.travis.yml'
  warning: no previously-included files found matching '*.rst.in'
  no previously-included directories found matching 'ci'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  writing manifest file 'python_rtmidi.egg-info/SOURCES.txt'
  running build_ext
  building 'rtmidi._rtmidi' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  creating build/temp.linux-x86_64-3.6/src/rtmidi
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D__RTMIDI_SILENCE_WARNINGS__ -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc/rtmidi -I/home/lattennn/tesi/include -I/usr/local/include/python3.6m -c src/_rtmidi.cpp -o build/temp.linux-x86_64-3.6/src/_rtmidi.o
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D__RTMIDI_SILENCE_WARNINGS__ -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc/rtmidi -I/home/lattennn/tesi/include -I/usr/local/include/python3.6m -c src/rtmidi/RtMidi.cpp -o build/temp.linux-x86_64-3.6/src/rtmidi/RtMidi.o
  src/rtmidi/RtMidi.cpp:1481:10: fatal error: alsa/asoundlib.h: No such file or directory
   1481 | #include <alsa/asoundlib.h>
        |          ^~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for python-rtmidi
  Running setup.py clean for python-rtmidi
Failed to build python-rtmidi
Installing collected packages: python-rtmidi
    Running setup.py install for python-rtmidi ... error
    ERROR: Command errored out with exit status 1:
     command: /home/lattennn/tesi/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uirkxdj2/install-record.txt --single-version-externally-managed --compile --install-headers /home/lattennn/tesi/include/site/python3.6/python-rtmidi
         cwd: /tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/
    Complete output (35 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/rtmidi
    copying rtmidi/__init__.py -> build/lib.linux-x86_64-3.6/rtmidi
    copying rtmidi/version.py -> build/lib.linux-x86_64-3.6/rtmidi
    copying rtmidi/midiconstants.py -> build/lib.linux-x86_64-3.6/rtmidi
    copying rtmidi/midiutil.py -> build/lib.linux-x86_64-3.6/rtmidi
    running egg_info
    writing python_rtmidi.egg-info/PKG-INFO
    writing dependency_links to python_rtmidi.egg-info/dependency_links.txt
    writing top-level names to python_rtmidi.egg-info/top_level.txt
    reading manifest file 'python_rtmidi.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '*.rst.in'
    no previously-included directories found matching 'ci'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'python_rtmidi.egg-info/SOURCES.txt'
    running build_ext
    building 'rtmidi._rtmidi' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/rtmidi
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D__RTMIDI_SILENCE_WARNINGS__ -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc/rtmidi -I/home/lattennn/tesi/include -I/usr/local/include/python3.6m -c src/_rtmidi.cpp -o build/temp.linux-x86_64-3.6/src/_rtmidi.o
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D__RTMIDI_SILENCE_WARNINGS__ -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc/rtmidi -I/home/lattennn/tesi/include -I/usr/local/include/python3.6m -c src/rtmidi/RtMidi.cpp -o build/temp.linux-x86_64-3.6/src/rtmidi/RtMidi.o
    src/rtmidi/RtMidi.cpp:1481:10: fatal error: alsa/asoundlib.h: No such file or directory
     1481 | #include <alsa/asoundlib.h>
          |          ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lattennn/tesi/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uirkxdj2/install-record.txt --single-version-externally-managed --compile --install-headers /home/lattennn/tesi/include/site/python3.6/python-rtmidi Check the logs for full command output.

**Comment by lattennn** [comment]
> @shyamalschandra Please open an issue at https://github.com/SpotlightKid/python-rtmidi/issues and paste the full command you are using when trying to install python-rtmidi and its full output. Also show the output of `dpkg-query -s libasound2-dev` and `dpkg-query -s libjack-jackd2-dev`.

Something updated. Now I am using Ubuntu 20.04 on VMwareWorkstationPlayer16 with all the requirements installed. But I still got the errors below:

(tesi) lattennn@ubuntu:~/Thesis/antonio$ pip3 install python-rtmidi
Collecting python-rtmidi
  Downloading python-rtmidi-1.4.6.tar.gz (247 kB)
     |████████████████████████████████| 247 kB 1.2 MB/s 
Building wheels for collected packages: python-rtmidi
  Building wheel for python-rtmidi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/lattennn/tesi/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-le3r8rvf
       cwd: /tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/
  Complete output (35 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/__init__.py -> build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/version.py -> build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/midiconstants.py -> build/lib.linux-x86_64-3.6/rtmidi
  copying rtmidi/midiutil.py -> build/lib.linux-x86_64-3.6/rtmidi
  running egg_info
  writing python_rtmidi.egg-info/PKG-INFO
  writing dependency_links to python_rtmidi.egg-info/dependency_links.txt
  writing top-level names to python_rtmidi.egg-info/top_level.txt
  reading manifest file 'python_rtmidi.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.travis.yml'
  warning: no previously-included files found matching '*.rst.in'
  no previously-included directories found matching 'ci'
  warning: no previously-included files matching '__pycache__' found under directory '*'
  warning: no previously-included files matching '*.py[co]' found under directory '*'
  writing manifest file 'python_rtmidi.egg-info/SOURCES.txt'
  running build_ext
  building 'rtmidi._rtmidi' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  creating build/temp.linux-x86_64-3.6/src/rtmidi
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D__RTMIDI_SILENCE_WARNINGS__ -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc/rtmidi -I/home/lattennn/tesi/include -I/usr/local/include/python3.6m -c src/_rtmidi.cpp -o build/temp.linux-x86_64-3.6/src/_rtmidi.o
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D__RTMIDI_SILENCE_WARNINGS__ -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc/rtmidi -I/home/lattennn/tesi/include -I/usr/local/include/python3.6m -c src/rtmidi/RtMidi.cpp -o build/temp.linux-x86_64-3.6/src/rtmidi/RtMidi.o
  src/rtmidi/RtMidi.cpp:1481:10: fatal error: alsa/asoundlib.h: No such file or directory
   1481 | #include <alsa/asoundlib.h>
        |          ^~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for python-rtmidi
  Running setup.py clean for python-rtmidi
Failed to build python-rtmidi
Installing collected packages: python-rtmidi
    Running setup.py install for python-rtmidi ... error
    ERROR: Command errored out with exit status 1:
     command: /home/lattennn/tesi/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uirkxdj2/install-record.txt --single-version-externally-managed --compile --install-headers /home/lattennn/tesi/include/site/python3.6/python-rtmidi
         cwd: /tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/
    Complete output (35 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/rtmidi
    copying rtmidi/__init__.py -> build/lib.linux-x86_64-3.6/rtmidi
    copying rtmidi/version.py -> build/lib.linux-x86_64-3.6/rtmidi
    copying rtmidi/midiconstants.py -> build/lib.linux-x86_64-3.6/rtmidi
    copying rtmidi/midiutil.py -> build/lib.linux-x86_64-3.6/rtmidi
    running egg_info
    writing python_rtmidi.egg-info/PKG-INFO
    writing dependency_links to python_rtmidi.egg-info/dependency_links.txt
    writing top-level names to python_rtmidi.egg-info/top_level.txt
    reading manifest file 'python_rtmidi.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '*.rst.in'
    no previously-included directories found matching 'ci'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    writing manifest file 'python_rtmidi.egg-info/SOURCES.txt'
    running build_ext
    building 'rtmidi._rtmidi' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    creating build/temp.linux-x86_64-3.6/src/rtmidi
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D__RTMIDI_SILENCE_WARNINGS__ -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc/rtmidi -I/home/lattennn/tesi/include -I/usr/local/include/python3.6m -c src/_rtmidi.cpp -o build/temp.linux-x86_64-3.6/src/_rtmidi.o
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D__RTMIDI_SILENCE_WARNINGS__ -D__LINUX_ALSA__ -D__UNIX_JACK__ -Isrc/rtmidi -I/home/lattennn/tesi/include -I/usr/local/include/python3.6m -c src/rtmidi/RtMidi.cpp -o build/temp.linux-x86_64-3.6/src/rtmidi/RtMidi.o
    src/rtmidi/RtMidi.cpp:1481:10: fatal error: alsa/asoundlib.h: No such file or directory
     1481 | #include <alsa/asoundlib.h>
          |          ^~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/lattennn/tesi/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-gpgefgua/python-rtmidi_91382b74cb5c4ea6a19e22949935a69c/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uirkxdj2/install-record.txt --single-version-externally-managed --compile --install-headers /home/lattennn/tesi/include/site/python3.6/python-rtmidi Check the logs for full command output.

**Comment by SpotlightKid** [comment]
1. I asked you to open an issue at https://github.com/SpotlightKid/python-rtmidi/issues, this issue is not the right place to discuss this, since your problem is not related to RtMidi, only to `python-rtmidi. They are separate projects.
2. I asked you to also post the output of `dpkg-query -s libasound2-dev` and `dpkg-query -s libjack-jackd2-dev`, which you haven't. This would have shown whether you really have the `libasound2-dev` and `libjack-jackd2-dev` packages installed.
3. The error in your output shows that you haven't installed the `libasound2-dev` package. Please install it and try again. If you still have problems, again, do not post it here, open a new issue in the [python-rtmidi](https://github.com/SpotlightKid/python-rtmidi/issues) project.

**Comment by lattennn** [comment]
> @shyamalschandra Please open an issue at https://github.com/SpotlightKid/python-rtmidi/issues and paste the full command you are using when trying to install python-rtmidi and its full output. Also show the output of `dpkg-query -s libasound2-dev` and `dpkg-query -s libjack-jackd2-dev`.

Thanks! I solved it!
