### ISSUE TITLE
Whether rtmidi provide the api to get the Unique Identification Number of hardware

### ISSUE THREAD

**Issue by masoria** [thestk/rtmidi#116]
We are doing a musical instrument game, using a number of the same type of equipment, I can get from the API port name, but the device name is always shaped like "E-Drum 0" or "E-Drum 1" (device name + index), and not sure which index corresponds to a specific instrument hardware, I need a API to get the only identify name of device, very anxious. using windows

**Comment by masoria** [comment]
using windows

**Comment by sagamusix** [comment]
The Windows MIDI API does not give you this kind of information, at least not the "classic" MIDI API doesn't. All you get are device names. Maybe the new and improved MIDI API in Windows 10 can do it, but rtmidi does not make use of this API.

**Comment by masoria** [comment]
@sagamusix 
So, can rtmidi be able to get the "device name + USB port"? Because the USB port and the device once fixed then I can clearly know which signal is from the user

**Comment by sagamusix** [comment]
No, the Windows MIDI API does not give you this kind of information. A MIDI input port doesn't even need to be an USB device (e.g. it could be a DIN plug on a dedicated audio interface), so such a mapping is not even guaranteed to exist.

**Comment by radarsat1** [comment]
It looks like some product/vendor ID information is available in the related MIDI*CAPS structs: https://msdn.microsoft.com/en-us/library/windows/desktop/dd798451(v=vs.85).aspx

**Comment by sagamusix** [comment]
These should be [MIDI vendor IDs](https://www.midi.org/specifications/item/manufacturer-id-numbers), which don't really help you with mapping devices. Maybe the product IDs do, but it's unlikely.

**Comment by radarsat1** [comment]
I agree that this would probably just lead to confusion.  Returning some kind of descriptor string beyond the device number could indeed be useful but I can't see how we could guarantee any kind of consistency across the huge array of vendors, devices, ports, operating systems, etc., so it's probably better not to have it.  I'll close unless a good proposal can be found.
