### ISSUE TITLE
API change to avoid unneccessary allocations

### ISSUE THREAD

**Issue by sagamusix** [thestk/rtmidi#118]
This topic is intended to discuss possible API changes for reducing the amount of possibly required heap allocations, which are especially problematic in real-time contexts, which MIDI I/O typically happens in.
I would be tempted to start implementing these changes if this API and ABI change is welcome.

Rationale: Currently the RtMidi API enforces messages to be passed as a `std::vector<unsigned char>`. No matter what internal representation the API user may use in their own codebase, they have to convert it to a vector. Contrary to `std::string`, `std::vector` does not have any small vector optimizations, meaning that for every single message that is passed to `sendMessage`, a tiny bit of heap memory has to be allocated. Even if the user wants to use `std::vector` with a custom allocator, the custom allocator has to be dropped when passing the data to RtMidi, because the custom allocator causes the two vector variants to be different types. So an extra copy when converting a vector with a custom allocator to a standard vector cannot be avoided.

Solution: There are already lightweight alternatives to `std::vector` that could be adopted for RtMidi. For example, [gsl::span](https://github.com/Microsoft/GSL) is really easy to implement and may eventually become part of the C++ standard, in which case it could be easily dropped into the RtMidi code.
Essentially, a `span` is just two pointers that point to the beginning and end of some data, but it is not mandated where this data resides (inside some heap object, in an array on the stack, etc.). It's basically a view into any memory, such as the content of a `std::vector` (so existing code can easily be changed to use the new API).
I would be interested to add a new `sendMessage` overload to the C++ API to use something like `gsl::span` if it can be agreed that adding new API overloads makes sense. Replacing the existing `std::vector` functions would break existing code for no good reason, so it should simply forward to the new API.

It would also be good to know which C++ language standard should be aimed for when implementing this, as modern C++11/14 would certainly make things easier but as far as I can see, this is currently not a requirement for RtMidi. Bumping the required compiler version might thus not be a welcome change.

**Comment by radarsat1** [comment]
I think a version taking std::array& would be welcome, but that also requires C++11.  I think probably a double* version is the best option.  I don't think adding a dependency on some 3rd-party library just for this is worth it however.

**Comment by sagamusix** [comment]
I didn't mean to suggest adding a dependency on gsl (which may become part of C++ in the future), but rather implementing a trivial version of `gsl::span` doing the most necessary stuff (adds only a couple dozen lines of code). Any contiguous STL container and `std::array` are trivially convertible to `gsl::span`, which makes its interface a good candidate for this task. I have almost finished a pull request, and as far as I can see it doesn't even require C++11.

**Comment by sagamusix** [comment]
Here's a first draft: https://github.com/sagamusix/rtmidi/commit/763cf48e8fd989b64ae7b0e13d575c84703c6723

**Comment by radarsat1** [comment]
I realize you just did a bunch of work there, but what is the need for a new data structure? It strikes me as a lot of code for not much gain.  Why not just have a version of getMessage that accepts double[] with a size?

Also, you bumped the version number for some reason.

Anyway, I've just been playing with the message queue, and I've realized there is already quite a bit of manipulation of std::vector happening, including push_back(), clear(), and copy semantics, during the incoming stream.  Replacing it with a simple limited-size array internally would be counterproductive for now.  So right now I don't think the overhead introduced by having to pass in an std::vector is very important compared to some of these dynamic push_backs and copies happening.  In short, the data is already on the heap anyway, so trying to streamline it with crazy classes so you can have your user-facing 4 bytes on the stack is not that beneficial without improving the FIFO correspondingly.

**Comment by sagamusix** [comment]
>  Why not just have a version of getMessage that accepts double[] with a size?

What exactly is a double[] supposed to do semantically? Are you seriously suggesting to encode byte sequences as floating-point or am I missing something?

> I realize you just did a bunch of work there, but what is the need for a new data structure? It strikes me as a lot of code for not much gain. 

I don't think it's a lot of code, but the huge gain is that the class RtMidiSpan can represent *any* container of bytes. The library user wants to keep using vectors of bytes? Great, they can do that. They want to use a `std::array`? Also no problem. They want to use plain old C arrays? That is also possible. They want to use whatever funky container they can come up with? That is also possible, as long as this container qualifies as a C++ container (actually requirements are much lower than those of a typical C++ container, only `size()`, `empty()` and `operator[]` are required).
This is basically the way modern C++ works, but technically this patch does not even require C++11 for that. It is much cleaner than, say, requiring the user to provide a pointer+size or begin+end iterators.

It would be possible to remove a bit of this generality but it would only remove a couple of lines of code (e.g. RtMidi does not require the `operator==` in my implementation, I just left it there for completeness' sake)

> Also, you bumped the version number for some reason.

Yes, because I added a function to the API, and assuming that RtMidi uses something like [Semantic Versioning](http://semver.org/), adding a new API function in a backwards-compatible manner mandates to bump the minor version.

**Comment by radarsat1** [comment]
> What exactly is a double[] supposed to do semantically? Are you seriously suggesting to encode byte sequences as floating-point or am I missing something?

Sorry, mistyped, I meant unsigned char[].  My point is that why not just provide an interface that takes a C array in addition to std::vector.  However, on further thought, I realized this doesn't even buy that much.  I'd have to see measurements to really believe that this is a bottleneck, given how the FIFO works.  I think deeper changes are necessary to really avoid std::vector and optimise the real-time guarantees, if it's important..

> They want to use whatever funky container they can come up with?

It's cool of course, but totally unnecessary for MIDI, which is just a bunch of unsigned chars at the end of the day.  Sorry but maintainers need to consider the cost of maintaining, and I don't think adding this much templated code just to wrap a simple array of bytes is really worth it.

> Yes, because I added a function to the API, and assuming that RtMidi uses something like Semantic Versioning, adding a new API function in a backwards-compatible manner mandates to bump the minor version.

This is only necessary for releases and is for the maintainers to do.

**Comment by sagamusix** [comment]
> I think deeper changes are necessary to really avoid std::vector and optimise the real-time guarantees, if it's important..

At least on Windows sendMessage doesn't do any allocations (unless you're sending a SysEx, which is typically not realtime), and apart from that, the `std::vector` that the user has to create for no good reason is the only source of heap allocations. In a typical mixing routine, these vectors could very well be the only allocations.

> It's cool of course, but totally unnecessary for MIDI, which is just a bunch of unsigned chars at the end of the day.

Which makes one wonder why it's a `std::vector` in the current interface to begin with. Of course you may just as well go with a pointer + data size instead, but that feels very outdated and less secure than a C++ container wrapper.

What I meant with "whatever funky container they can come up with" is not that we would want to support any bizzare container. What I rather meant is that there are many ways people might be storing their messages, which are not necessary one of std::vector, std::array or plain old C array. They might be using some class which abstracts away the storage, and as long as this class conforms to C++ container interfaces, it would be trivial to directly use it with RtMidi without the need to do any extra data manipulation.

> This is only necessary for releases and is for the maintainers to do.

Yes, which is why I was mentioning earlier that it should probably not be done in the PR (if I ever get to make one after these arguments). I was just putting it in the commit to remind that this needs to be done.

**Comment by radarsat1** [comment]
If you can manage a simple version of sendMessage that just takes an unsigned char[] + size, I think it would be a really useful contribution.  Sorry for being hesitant to introduce complexity, I think the work you did is great, just not appropriate to this codebase.  I apologize in advance if I can't respond immediately in the next couple of days, I'll be busy in a workshop.

(For the future I am recommending to @garyscavone to start an experimental branch for more modern/advanced C++ usage, where such ideas will be certainly more welcome!)

**Comment by sagamusix** [comment]
Okay, I will modify the patch to accept a pointer+size then.
I am contemplating whether this should be a `void*` or `unsigned char*`. The rationale is that some library users may simply be usigned `char` instead of `unsigned char` for storing their MIDI messages (our code did this for a long time). `void*` would allow to use signed chars as well, but it would be less type-safe, so it might not be a favorable solution.

**Comment by sagamusix** [comment]
New try: https://github.com/sagamusix/rtmidi/commit/837d6ad7a1c984102db30179c65bb66dbaf1af89

**Comment by radarsat1** [comment]
I fixed the sendMessage prototype for alsa here: https://github.com/radarsat1/rtmidi/tree/no-allocations

I ran the midiout example and it seems to work.  Haven't run any sysex tests.
 
@garyscavone I think this is a useful contribution, what do you think?  Keeps the std::vector interface but allows for passing in a simple C-style array as well.

**Comment by radarsat1** [comment]
Sorry wait I just found that this breaks the Jack build.

**Comment by radarsat1** [comment]
No, my mistake again. The jack build is broken on master :(
working on it..

**Comment by radarsat1** [comment]
Fixed, sorry, it was unrelated.

**Comment by sagamusix** [comment]
Thanks for the fix and pull request!

**Comment by radarsat1** [comment]
#120 merged, so I'll close this.  Thanks @sagamusix, hopefully this is adequate for now to make it possible to use sendMessage() on stack data, we can consider further enhancements at a later time.
