### ISSUE TITLE
Unable to pass compile flags when building RtMidi.o and rtmidi_c.o

### ISSUE THREAD

**Issue by AndrewBelt** [thestk/rtmidi#132]
- Expected behavior and actual behavior.

When exporting CFLAGS, CXXFLAGS, and LDFLAGS (for something like `-mmacosx-version-min=10.7` on Mac), normally these are passed to the `./configure` script and Makefile when running `make`. I don't know autoconf, but something is preventing these flags from being used when building RtMidi.o and rtmidi_c.o.

- Steps to reproduce the problem.

    export CFLAGS="-mmacosx-version-min=10.7"
    export CXXFLAGS="-mmacosx-version-min=10.7"
    export LDFLAGS="-mmacosx-version-min=10.7"
    ./configure
    make

gives "object file (./libs/RtMidi.o) was built for newer OSX version (10.12) than being linked (10.7)" because half of the files are being compiled with the exported flags and half without.

- Specifications like the version of the project, operating system, or hardware.

Using MacOS 10.12 with rtmidi 3.0.0 source tarball.

**Comment by radarsat1** [comment]
The offending line is [103 in configure.ac](https://github.com/thestk/stk/blob/master/configure.ac#L103), I think, `CXXFLAGS="$cxxflag"`

**Comment by AndrewBelt** [comment]
Looks like that's it! I could never figure out which of the files is generated by autoconf/autotools/automake/configure/whatever it's called and which is human-written.

**Comment by radarsat1** [comment]
There is a patch to fix this in #131, but it is very bare, just puts it back to how it was.  I think a better fix is forthcoming.

**Comment by radarsat1** [comment]
This should be fixed with the recent Debian-related patches to configure.ac I think.
