### ISSUE TITLE
Is there any way to open default MIDI port on macOS like windows 10?

### ISSUE THREAD

**Issue by onlyfly34** [thestk/rtmidi#135]
On windows 10, with winmm.lib, I can use a default MIDI port named "microsoft gs wavetable synth".
With that, my PC can generate sounds with test program (midiout.cpp), although sound isn't pretty good.

Is it possible to achieve similar goals on macOS with coreMIDI library?

**Comment by radarsat1** [comment]
I don't know if there is a default MIDI synth on OS X, but your program should look for the port you want to open and open it.  You can use RtMidiOut::getPortName() to get names of all ports.  If you want to open a running MIDI synth you should be able to find it by name that way.

**Comment by radarsat1** [comment]
Closing due to age.
