### ISSUE TITLE
Cannot find entry point (C API macOS)

### ISSUE THREAD

**Issue by micdah** [thestk/rtmidi#137]
I am having difficult compiling rtmidi on macOS after recent changes to `Makefile.am` and `configure.ac`, it seems the exposed C methods are being garbled where they weren't previously (_I am using rtmidi from managed code via P/Invoke_).

If I revert these to files to there state in commit `d19b7573f7274edbfe8ece52fae482c66094d767`, I have no issue compiling and using the C-methods from managed code.

This is how I compile rtmidi:
```
# ./autogen.sh --no-configure
# ./configure
# make
```

I am using the produced `.libs/librtmidi.dylib` file.

**Comment by radarsat1** [comment]
Can you possibly do a bisect and find where the problem occurs?  The commit you indicate only changes some lines in `README.md`.

**Comment by micdah** [comment]
Oops forgot to mention, the error I am receiving is _"Unable to find entry point `method_name` in DLL rtmidi"_

**Comment by micdah** [comment]
I suspect it is one of the commits after that point (there are a handfull recently changing both these files), so my debugging only led me to try and specifically pick these version `git checkout d19b7573f7274edbfe8ece52fae482c66094d767 Makefile.am` (and likewise for `configure.ac`) and after doing this, I can observe that I no longer have this issue and rtmidi seems to function correctly in my application.

I can dump a diff here, if that helps?

There are a great deal of changes, so I am having a difficult time pinpointing the smoking gun, so to speak.

**Makefile.am diff**
```
diff --git a/Makefile.am b/Makefile.am
index 2bbb17c..1606cc7 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -3,8 +3,6 @@ if MAKE_DOC
SUBDIRS += doc
endif

AM_CXXFLAGS = @visibility@

lib_LTLIBRARIES = %D%/librtmidi.la
%C%_librtmidi_la_LDFLAGS = -no-undefined -export-dynamic -version-info @SO_VERSION@
%C%_librtmidi_la_SOURCES = \
```

**configure.ac diff**
```
diff --git a/configure.ac b/configure.ac
index 4390648..2474c4c 100644
--- a/configure.ac
+++ b/configure.ac
@@ -27,49 +27,31 @@ m4_define([lt_current_minus_age], [m4_eval(lt_current - lt_age)])

SO_VERSION=lt_version_info
AC_SUBST(SO_VERSION)
AC_SUBST(LIBS)
AC_SUBST(api)
AC_SUBST(req)
AC_SUBST(visibility)

visibility=""
api=""
req=""

# Fill GXX with something before test.
GXX="no"

# if the user did not provide any CXXFLAGS, we can override them
AS_IF([test "x$CXXFLAGS" = "x" ], [override_cxx=yes], [override_cxx=no])
AS_IF([test "x$CFLAGS" = "x" ], [override_c=yes], [override_c=no])

# Check version number coherency between RtMidi.h and configure.ac
AC_MSG_CHECKING([that version numbers are coherent])
RTMIDI_VERSION=`sed -n 's/#define RTMIDI_VERSION "\(.*\)"/\1/p' $srcdir/RtMidi.h`
AS_IF(
   [test "x$RTMIDI_VERSION" != "x$PACKAGE_VERSION"],AC_RUN_IFELSE(
   [AC_LANG_PROGRAM([#include <string.h>
                     `grep "define RTMIDI_VERSION" $srcdir/RtMidi.h`],
                    [return strcmp(RTMIDI_VERSION, PACKAGE_VERSION);])],
   [AC_MSG_RESULT([yes])],
   [AC_MSG_FAILURE([testing RTMIDI_VERSION==PACKAGE_VERSION failed, check that RtMidi.h defines RTMIDI_VERSION as "$PACKAGE_VERSION" or that the first line of configure.ac has been updated.])])

# Enable some nice automake features if they are available
m4_ifdef([AM_MAINTAINER_MODE], [AM_MAINTAINER_MODE])
m4_ifdef([AM_SILENT_RULES], [AM_SILENT_RULES([yes])])

# configure flags
AC_ARG_ENABLE([debug], [AS_HELP_STRING([--enable-debug], [enable various debugging output])])
AC_ARG_WITH(jack, [AS_HELP_STRING([--with-jack], [choose JACK server support (mac and linux only)])])
AC_ARG_WITH(alsa, [AS_HELP_STRING([--with-alsa], [choose native ALSA sequencer API support (linux only)])])
AC_ARG_WITH(core, [AS_HELP_STRING([--with-core], [ choose CoreMidi API support (mac only)])])
AC_ARG_WITH(winmm, [AS_HELP_STRING([--with-winmm], [ choose Windows MultiMedia (MM) API support (win32 only)])])
AC_ARG_WITH(winks, [AS_HELP_STRING([--with-winks], [  choose kernel streaming support (win32 only)])])Fill GXX with something before test.
AC_SUBST( GXX, ["no"] )
AC_SUBST(noinst_LIBRARIES)

# Checks for programs.
AC_PROG_CXX(g++ CC c++ cxx)
AM_PROG_AR
AC_PATH_PROG(AR, ar, no)
AS_IF([test "x$AR"if [[ $AR = "xno"], [
    AC_MSG_ERROR([Could"no" ]] ; then
    AC_MSG_ERROR("Could not find ar - needed to create a library])
])library");
fi

LT_INIT([win32-dll])
AC_CONFIG_MACRO_DIR([m4])
@@ -85,35 +67,32 @@ AC_CHECK_HEADER([semaphore.h], [
    AC_MSG_WARN([POSIX semaphore support not found; data may be lost on closePort]))
])

# checkCheck for debug
AC_MSG_CHECKING(whether to compile debug version)
debugflags=""
object_path=Release
AS_CASE([${enable_debug}],AC_ARG_ENABLE(debug,
  [  yes ], [
    AC_MSG_RESULT([yes])
    CPPFLAGS="-D__RTMIDI_DEBUG ${CPPFLAGS}"
    debugflags="${debugflags} -g"
    object_path=Debug
  ],
  [ no ], [
    AC_MSG_RESULT([no!])
    debugflags="${debugflags} -O3"
  ], [
    AC_MSG_RESULT([no])
  ])--enable-debug = enable various debug output],
  [AC_SUBST( cppflag, [-D__RTMIDI_DEBUG__] ) AC_SUBST( cxxflag, [-g] ) AC_SUBST( object_path, [Debug] ) AC_MSG_RESULT(yes)],
  [AC_SUBST( cppflag, [] ) AC_SUBST( cxxflag, [-O3] ) AC_SUBST( object_path, [Release] ) AC_MSG_RESULT(no)])

# Set paths if prefix is defined
if test "x$prefix" != "x" && test "x$prefix" != "xNONE"; then
  LIBS="$LIBS -L$prefix/lib"
  CPPFLAGS="$CPPFLAGS -I$prefix/include/rtmidi"
fi

# For -I and -D flags
CPPFLAGS="$CPPFLAGS $cppflag"

# For debugging and optimization ... overwrite default because it has both -g and -O2
AS_IF([test "x$debugflags" != x],
  AS_IF([test "x$override_cxx" = "xyes" ], CXXFLAGS="$CXXFLAGS $debugflags", CXXFLAGS="$debugflags $CXXFLAGS")
  AS_IF([test "x$override_c" = "xyes" ], CFLAGS="$CFLAGS $debugflags", CFLAGS="$debugflags $CFLAGS")
  )#CXXFLAGS="$CXXFLAGS $cxxflag"
CXXFLAGS="$cxxflag"

# Check compiler and use -Wall if gnu.
AS_IF([test "x$GXX"if [test $GXX = "xyes"], [
  CXXFLAGS="-Wall -Wextra ${CXXFLAGS}"
  AS_IF([test "x${enable_debug}" != "xyes" ], visibility="-fvisibility=hidden""yes" ;] then
  AC_SUBST( cxxflag, ["-Wall -Wextra"] )
])fi

CXXFLAGS="$CXXFLAGS $cxxflag"

# Checks for doxygen
AC_CHECK_PROG( DOXYGEN, [doxygen], [doxygen] )
@@ -129,12 +108,12 @@ AC_CONFIG_LINKS( [doc/images/mcgill.gif:doc/images/mcgill.gif] )
# Checks for package options and external software
AC_CANONICAL_HOST

AC_SUBST( api, [""] )
AC_SUBST( req, [""] )
AC_MSG_CHECKING(for MIDI API)

AC_ARG_WITH(jack, [  --with-jack = choose JACK server support (mac and linux only)])
AS_IF([test "x$with_jack" === "xyes"], [
api="$api -D__UNIX_JACK__"
AC_MSG_RESULT(using JACK)
AC_CHECK_LIB(jack, jack_client_open, , AC_MSG_ERROR(JACK support requires the jack library!))])
@@ -142,19 +121,19 @@ AC_CHECK_LIB(jack, jack_client_open, , AC_MSG_ERROR(JACK support requires the ja
case $host in
  *-*-linux*)
  # Look for ALSA flag
  AC_ARG_WITH(alsa, [  --with-alsa = choose native ALSA sequencer API support (linux only)])
  AS_IF([test "x$with_alsa" === "xyes"], [AC_MSG_RESULT(using ALSA)
    AC_CHECK_LIB(asound, snd_seq_open, , AC_MSG_ERROR(ALSA support requires the asound library!))
    api="$api -D__LINUX_ALSA__"
    req="$req alsa"
    ])AC_MSG_RESULT(using ALSA)
    AC_CHECK_LIB(asound, snd_seq_open, , AC_MSG_ERROR(ALSA support requires the asound library!))])

  AS_IF([test "x${api}" = "x"],if [test "$api" == "";] then
    AC_MSG_RESULT(using ALSA)
    AC_CHECK_LIB(asound, snd_seq_open, , AC_MSG_ERROR(ALSA sequencer support requires the asound library!))
    api="-D__LINUX_ALSA__ ${api}"AC_SUBST( api, [-D__LINUX_ALSA__] )
    req="$req alsa"
    )AC_CHECK_LIB(asound, snd_seq_open, , AC_MSG_ERROR(ALSA sequencer support requires the asound library!))
  fi

  # Checks for pthread library.
  AC_CHECK_LIB(pthread, pthread_create, , AC_MSG_ERROR(RtMidi requires the pthread library!))
@@ -162,48 +141,48 @@ case $host in

  *-apple*)
  # Look for Core flag
  AC_ARG_WITH(core, [  --with-core = choose CoreMidi API support (mac only)])
  AS_IF([test "x$with_core" === "xyes"], [
    api="$api -D__MACOSX_CORE__"
    AC_MSG_RESULT(using CoreMidi)
    AC_CHECK_HEADER(CoreMIDI/CoreMIDI.h, [], [AC_MSG_ERROR(CoreMIDI header files not found!)] )
    LIBS="-frameworkLIBS="$LIBS -framework CoreMIDI -framework CoreFoundation -framework CoreAudio ${LIBS}"
    api="$api -D__MACOSX_CORE__"CoreAudio" ])

  # If no api flags specified, use CoreMidi
  AS_IF([test "x${api}" = "x"],if [test "$api" == ""; ] then
    AC_SUBST( api, [-D__MACOSX_CORE__] )
    AC_MSG_RESULT(using CoreMidi)
    AC_CHECK_HEADER(CoreMIDI/CoreMIDI.h,
      [],
      [AC_MSG_ERROR(CoreMIDI header files not found!)] )
    LIBS="-frameworkAC_SUBST( LIBS, ["-framework CoreMIDI -framework CoreFoundation -framework CoreAudio ${LIBS}"
    api="$api -D__MACOSX_CORE__"CoreAudio"] )
  fi
  ;;

  *-mingw32*)
  # Look for WinMM flag
  AC_ARG_WITH(winmm, [  --with-winmm = choose Windows MultiMedia (MM) API support (windoze only)])
  AS_IF([test "x$with_winmm" === "xyes"], [AC_MSG_RESULT(using WinMM)
    LIBS="-lwinmm ${LIBS}"
    api="$api -D__WINDOWS_MM__"
    ])AC_MSG_RESULT(using WinMM)
    AC_SUBST( LIBS, [-lwinmm] )])

  AC_ARG_WITH(winks, [  --with-winks = choose kernel streaming support (windoze only)])
  AS_IF([test "x$with_winks" === "xyes"], [AC_MSG_RESULT(using kernel streaming)
    LIBS="-lsetupapi -lksuser ${LIBS}"
    api="$api -D__WINDOWS_KS__"
    AC_SUBST( LIBS, ["-lsetupapi -lksuser"] )
    AC_MSG_RESULT(using kernel streaming) ])

  # I can't get the following check to work so just manually add the library
	# or could try the following?  AC_LIB_WINMM([midiOutGetNumDevs])
  # AC_CHECK_LIB(winmm, midiInGetNumDevs, , AC_MSG_ERROR(Windows MIDI support requires the winmm library!) )],)

  # If no api flags specified, use WinMM
  AS_IF([test "x${api}" = "x"], [if [test "$api" == "";] then
    AC_SUBST( api, [-D__WINDOWS_MM__] )
    AC_MSG_RESULT(using WinMM)
    LIBS="-lwinmm ${LIBS}"
    api="${api} -D__WINDOWS_MM__"
  ])AC_SUBST( LIBS, [-lwinmm] )
  fi
  ;;

  *)

```

**Comment by radarsat1** [comment]
> Unable to find entry point method_name in DLL rtmidi

I find this confusing.  I haven't had a chance to test on Mac yet, but you say that it's a MacOS problem, yet your error report talks about DLLs.  Have you tried "git bisect" to find the problem?  Logically this should be related somehow to "extern" or to the RTMIDI_DLL_PUBLIC macro or something like that.

It might help if you say what "method_name" is not found.  In the meantime I have tried compiling with both gcc and clang on Linux and used the `nm` utility to check the results and the names of functions in the C API do not appear to be mangled:

```
$ nm .libs/librtmidi.so.4.0.0 | grep rtmidi_
00000000000066a0 t _GLOBAL__sub_I_rtmidi_c.cpp
000000000000c360 T rtmidi_close_port
000000000000bd60 T rtmidi_get_compiled_api
000000000000c390 T rtmidi_get_port_count
000000000000c3d0 T rtmidi_get_port_name
000000000000c7e0 T rtmidi_in_cancel_callback
000000000000c570 T rtmidi_in_create
000000000000c440 T rtmidi_in_create_default
000000000000c6f0 T rtmidi_in_free
000000000000c720 T rtmidi_in_get_current_api
000000000000c850 T rtmidi_in_get_message
000000000000c830 T rtmidi_in_ignore_types
000000000000c740 T rtmidi_in_set_callback
000000000000c120 T rtmidi_open_port
000000000000c240 T rtmidi_open_virtual_port
000000000000ca50 T rtmidi_out_create
000000000000c930 T rtmidi_out_create_default
000000000000cbd0 T rtmidi_out_free
000000000000cbf0 T rtmidi_out_get_current_api
000000000000cc10 T rtmidi_out_send_message
000000000000bf60 T _Z12rtmidi_errorP7MidiApi15RtMidiErrorTypePKc
```

Also I am able to compile and run a small C problem against it.  I assume it is your user program that is reporting the error at load time but I cannot tell from your bug report.  I'll test on Mac when I get the chance.

**Comment by micdah** [comment]
Yes, my apologies, the method in question is `rtmidi_get_compiled_api`, the reason I am mentioning DLL is because my user application is a .Net Core application using `DllImport` (_naming convention not so great now that we are cross-platform 😄 _).

I suspect it is a macOS issue, as my user application works fine on Windows.

Good idea to look at the symbols in the compiled .dylib, so using your idea this is the result when building using the latest `Makefile.am` and `configure.ac`:
```
[micdah ~/git/rtmidi]> nm .libs/librtmidi.dylib | grep rtmidi
0000000000005dc0 t __Z12rtmidi_errorP7MidiApi15RtMidiErrorTypePKc
0000000000006110 t _rtmidi_close_port
0000000000005b80 t _rtmidi_get_compiled_api
0000000000006150 t _rtmidi_get_port_count
0000000000006190 t _rtmidi_get_port_name
00000000000065d0 t _rtmidi_in_cancel_callback
0000000000006330 t _rtmidi_in_create
0000000000006210 t _rtmidi_in_create_default
00000000000064c0 t _rtmidi_in_free
0000000000006500 t _rtmidi_in_get_current_api
0000000000006650 t _rtmidi_in_get_message
0000000000006630 t _rtmidi_in_ignore_types
0000000000006520 t _rtmidi_in_set_callback
0000000000005ef0 t _rtmidi_open_port
0000000000006010 t _rtmidi_open_virtual_port
0000000000006850 t _rtmidi_out_create
0000000000006740 t _rtmidi_out_create_default
00000000000069d0 t _rtmidi_out_free
0000000000006a00 t _rtmidi_out_get_current_api
0000000000006a20 t _rtmidi_out_send_message
0000000000005b70 t _rtmidi_sizeof_rtmidi_api
```

I notice that mine differs to yours, in that a `_` have been prefixed to each method, thus probably causing my issue as my managed code expects a different C method name.

**Comment by radarsat1** [comment]
Huh.  That is weird.  Maybe there is a `_declspec` that is needed, but I don't see what's different with the configuration.

**Comment by micdah** [comment]
Well, just out of curiosity I did a `nm` on the dylib that is working, compiled with the old versions - and this also has the exact same names in the symbol table, with `_` prefixes.

But for some strange reason, this version works whereas the other doesn't.

But the two are not binary identical, so the two buildfiles indeed do produce different output files, so something in the new version confuses `DllImport` in .Net Core. Rather strange.

**Comment by radarsat1** [comment]
Oh I believe you that there is a difference, but you'll have to experiment a bit to figure out more precisely what has changed, since I can't seem to detect it on my end unfortunately.  The only thing I can think of is that RTMIDI_DLL_PUBLIC stuff, but afaik that did not affect the C API.  You might try playing with that and inserting `extern "C"` in some places..

**Comment by micdah** [comment]
I tried `git bisect` (excellent git command btw, did not know of it until now), this is my findings:
```
[micdah ~/git/rtmidi]> git bisect bad
31943b30c870f4b1d827c610bd85cde4a68661a5 is the first bad commit
commit 31943b30c870f4b1d827c610bd85cde4a68661a5
Author: IOhannes m zmölnig <zmoelnig@umlautQ.umlaeute.mur.at>
Date:   Mon Oct 9 22:58:46 2017 +0200

    Fixed some more class-exports for visibility=hidden

:100644 100644 22946829f838ded291dc56901a680ffcdd941129 5ea2425cfa92f199f3c9fec465390fba11bee964 M	RtMidi.h
```

**Comment by micdah** [comment]
Hmm, seems I did something wrong with bisect, it is actually the commit just after the one above, where it breaks. So at `31943b30c870f4b1d827c610bd85cde4a68661a5` (the above commit) it works, but on the next commit `0470e7c5e5fc70ca22351883cab76c8e1222438a` it breaks.

**Comment by micdah** [comment]
Just tried to compile using the latest versions of `Makefile.am` and `configure.ac` where I reverted that specific commit, and this produces a `.dylib` file which works.

So something in these changes, or things the changes affects, seems to cause issues. Seems P/Invoke specific though, as I have tested the `tests/cmidiin` program and this seems to work in all cases - but my .Net Core user application does not like all versions 😄

**Comment by micdah** [comment]
My best guess is that the `-fvisibility=hidden` somehow affects the C-methods exposed? Maybe P/Invoke respects that they somehow have been marked as hidden?

I am clearly not a proficient C/C++ developer, so I am guessing quite a bit here. 😄

**Comment by micdah** [comment]
It seems likely to be the cause, reading at https://gcc.gnu.org/wiki/Visibility as far as I can tell this argument changes default visibility to `hidden` unless otherwise stated.

But the C-api methods aren't declared at not hidden, so wouldn't this attribute make them hidden in the resulting assembly file?

**Comment by radarsat1** [comment]
Yes, definitely that could be related.  Did you try removing it?

**Comment by micdah** [comment]
Yes, reverting the [commit](https://github.com/thestk/rtmidi/commit/0470e7c5e5fc70ca22351883cab76c8e1222438a) seems to "fix" the issue.

Of course it seems like something one would like to have in a production build dll, but I am unsure what is needed to make `-fvisibility` to work together with the exposed C-methods.

_The commit specifically only adds the `-fvisibility` option to `AM_CXXFLAGS`_

**Comment by micdah** [comment]
Here are the diff's between the working versions I am using, against `master`:

[`Makefile.am`](https://github.com/thestk/rtmidi/compare/master...micdah:master#diff-c949f93d03f44a4217d7a138f9e2e54a)
[`configure.ac`](https://github.com/thestk/rtmidi/compare/master...micdah:master#diff-67e997bcfdac55191033d57a16d1408a)

**Comment by radarsat1** [comment]
Okay cool.  I'll definitely consider reverting the visibility patch, if no one chimes in with some info on how to fix it properly.  By the way what compiler are you using, clang or gcc?

And, just to be very, very clear, you are saying that if you are on master, then,

~~~
git checkout master
git reset --hard
./autogen.sh
make
~~~

results in a non-working build, but if you do,

~~~
git checkout master
git reset --hard
git revert 0470e7c5e5fc70ca22351883cab76c8e1222438a
./autogen.sh
make
~~~

then it results in a working build?

**Comment by micdah** [comment]
Yes that is correct, the exact commands I use to build are:
```
./autogen.sh --no-configure
./configure
make
```

As far as I can tell, autogen defaults to debug build, so doing this ensures the resulting build isn't a debug build. As far as I can see, the visibility attribute is only added when not building a debug build. So it seems important to use `--no-configure`.

**Comment by radarsat1** [comment]
You are right, thanks for pointing that out.

**Comment by micdah** [comment]
I can make a branch with the changes that seems to make it work, just to be entirely sure we are talking about the correct changes 😄

**Comment by micdah** [comment]
@radarsat1 I have created this PR https://github.com/thestk/rtmidi/pull/139

And to be extremely sure, I have compiled first a clean branch identical to your `master` and confirmed the issue was present, then performed the ´git revert 0470e7c5e5fc70ca22351883cab76c8e1222438a` and re-compiled and confirmed this removed the issue I was experiencing.

**Comment by micdah** [comment]
Btw. this is the project in question that I am working on which uses the C-API methods of rtmidi https://github.com/micdah/RtMidi.Core

Working on a .Net Core wrapper around rtmidi, as MIDI support for .Net (_especially cross-platform support_) is scarce and often buggy, so basing it on rtmidi which is cross-platform in nature, seems like a good path.

**Comment by radarsat1** [comment]
Thanks for the link, I don't know all that much about .Net but I wonder if that's even possible to test on Linux.
It seems we are slowly collecting such bindings in the "contrib" folder so maybe we can put things together eventually.

For this PR, I will just wait a bit to see if there are any comments from the people who organized the 0470e7c patch before merging, but I might merge it tomorrow if there are no comments since I am away next week.

**Comment by micdah** [comment]
I haven't yet built a `.so` on a Linux box, but .Net Core works on major Linux distributions so in theory it should be possible to reproduce the issue there.

My only *NIX boxes in the house are macOS based though, so I haven't got any Linux boxes up and running at the moment. 😲

**Comment by micdah** [comment]
There is no hurry on my part regarding the PR and merging it, as I have already reverted the commit in my fork - but of course it would be best for me to follow your repository as close as possible, so would be great to get eventually merged or a better solution found. 😄 

(_Reason for using my own fork, is mainly as I have updated the  `.sln` as I use VS2017 and upgraded the proj files as these have also changed a bit, as well as changing the resulting Windows .dll to a dynamic library rather than a static_)

**Comment by radarsat1** [comment]
I'll close this now, since we temporarily reverted the offending commit, but please open a new issue if similar problems are encountered in the future, since I guess we'll try to find a way to fix the visibility issue eventually.  Thanks!  I'll try to find a reliable way to test for this.
