### ISSUE TITLE
Allow build on non-linux architectures

### ISSUE THREAD

**Issue by miramikes** [thestk/rtmidi#140]
Hi,

following patch allow rtmidi to be build on non-linux archs as hurd-i386 kfreebsd-amd64 kfreebsd-i386.
You might be interested to apply it upstream.

mira
[0001-kfreebsd-hurd.txt](https://github.com/thestk/rtmidi/files/1424300/0001-kfreebsd-hurd.txt)

**Comment by garyscavone** [comment]
@radarsat1 Perhaps this can be added to the configure script?
