### ISSUE TITLE
Risky calls to virtual functions inside constructor and destructor

### ISSUE THREAD

**Issue by rsjaffe** [thestk/rtmidi#143]
Are these intentional? Seems like this could cause difficult-to-trace bugs in some implementations (e.g., when a base pointer is used).

Examples:
line 2136 RtMidi.cpp in MidiInWinMM constructor, a call to _initialize_.
line 2142 RtMidi.cpp in MidiInWinMM destructor, a call to _closePort_.
line 2324 RtMidi.cpp in MidiOutWinMM constructor: _initialize_.
line 2330 RtMidi.cpp in MidiOutWinMM destructor: _closePort_.

**Comment by rsjaffe** [comment]
Looks like adding the _final_ specifier to the derived classes would allow predictable behavior with the calls. See https://www.securecoding.cert.org/confluence/display/cplusplus/OOP50-CPP.+Do+not+invoke+virtual+functions+from+constructors+or+destructors . Guess that's another change for when the project goes to C++11 compliance.

**Comment by radarsat1** [comment]
I agree that this could be a potential issue. I am not aware of it causing any problems, and the resource allocation/deallocate is very useful in the constructors/destructors.  If a non-C++11 solution can be found that would be preferred, but I hesitate to sacrifice the convenience of avoiding explicit calls to open/close ports.  Perhaps it is sufficient to be "very careful" that the virtual calls are made in the right order, since it doesn't appear to cause any problems at the moment.

**Comment by rsjaffe** [comment]
I agree with your comments. One potential solution would be to have a non-virtual private function in the derived classes that provides the same action as the current virtual functions. This would have implications if there were classes derived from your classes, but we'd have the same issue with using the _final_ keyword.  If/when you're going to C++11, I'd suggest only adding _final_ to the _initalize_ and _closePort_ methods, rather than to the whole class, as that would still allow the ability to derive a class, just without virtually overriding _initialize_ and _closePort_.

**Comment by radarsat1** [comment]
>  One potential solution would be to have a non-virtual private function in the derived classes that provides the same action as the current virtual functions.

It took me a while to figure this out, but I think what you're proposing is that each derived class should call its own closePort() etc,. instead of doing it in the abstract class.  This actually makes a lot of sense and doesn't change the API, so maybe worth trying.

**Comment by rsjaffe** [comment]
It looks like another way to do this pre C++11 is to qualify the call with the derived class's ID.

For example, in MidiInWinMM constructor, instead of a call to initialize, you'd call MidiInWinMM::initialize.

See http://en.cppreference.com/w/cpp/language/virtual

**Comment by radarsat1** [comment]
Closed in 95e24378bbbb7dc1debb24534bef34259ff7df8e?
