### ISSUE TITLE
Compiling with g++ 7.1 on macos 10.12.6

### ISSUE THREAD

**Issue by JeremyCooper** [thestk/rtmidi#148]
Compiling with the pre-installed g++ on my machine works as expected, however, when trying to compile the same program (in this case, the example program 'midiprobe') with g++-7.1, the linker is unable to make sense of the symbols.

OS: macOS Sierra 10.12.6
rtmidi: version 3.0.0 (obtained with `brew install rtmidi`)

Native:
`$ g++ --version`
`Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

Version 7.1:
`$ g++-7.1 --version`
`g++-7.1 (GCC) 7.1.0`

Compilation command used for both compilers is:
`[g++] -lrtmidi -D__MACOSX_CORE__ -o midiprobe midiprobe.cpp`

Compilation succeeds without error message for native g++.

Compilation with g++-7.1 yields:
`Undefined symbols for architecture x86_64:
  "RtMidi::getCompiledApi(std::vector<RtMidi::Api, std::allocator<RtMidi::Api> >&)", referenced from:
      _main in ccQizcGQ.o
  "RtMidiIn::RtMidiIn(RtMidi::Api, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)", referenced from:
      _main in ccQizcGQ.o
  "RtMidiOut::RtMidiOut(RtMidi::Api, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)", referenced from:
      _main in ccQizcGQ.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status`

Any suggestions or ideas would be greatly appreciated.

**Comment by radarsat1** [comment]
I say that it compiles fine for me in Linux with gcc-7.2.  It really sounds like .o files from different versions of the compiler are getting mixed up, but assuming you're controlling for that (make sure you "make clean" or even "git clean" completely), you'll have to use `nm` and other tools to investigate.  I don't think it's likely this is specific to RtMidi.

**Comment by JeremyCooper** [comment]
No issues compiling on my linux machine. I have been re-cloning the repo in-between attempts so I don't think it's an issue with leftover object files from previous compilations (is this what you meant?).
Here is something that perhaps sheds some light on what's going wrong.
If I try to pull the source file into the compile command instead of linking against the brew library, like so:
`g++-7.1 -D__MACOSX_CORE__ -o midiprobe midiprobe.cpp ../RtMidi.cpp`
I get some errors that I do not understand:
`In file included from /System/Library/Frameworks/CoreMIDI.framework/Headers/CoreMIDI.h:18:0,
                 from ../RtMidi.cpp:437:
/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:300:2: error: expected unqualified-id before ‘^’ token
 (^MIDINotifyBlock)(const MIDINotification *message);
  ^
/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:300:2: error: expected ‘)’ before ‘^’ token
/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:343:2: error: expected unqualified-id before ‘^’ token
 (^MIDIReadBlock)(const MIDIPacketList *pktlist, void * __nullable srcConnRefCon);
  ^
/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:343:2: error: expected ‘)’ before ‘^’ token
In file included from /System/Library/Frameworks/CoreMIDI.framework/Headers/CoreMIDI.h:18:0,
                 from ../RtMidi.cpp:437:
/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1154:6: error: ‘MIDINotifyBlock’ has not been declared
      MIDINotifyBlock __nullable notifyBlock )   __OSX_AVAILABLE_STARTING(__MAC_10_11, __IPHONE_9_0);
      ^~~~~~~~~~~~~~~
/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1240:9: error: ‘MIDIReadBlock’ has not been declared
         MIDIReadBlock readBlock ) __OSX_AVAILABLE_STARTING(__MAC_10_11, __IPHONE_9_0);
         ^~~~~~~~~~~~~
/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIServices.h:1643:9: error: ‘MIDIReadBlock’ has not been declared
         MIDIReadBlock   readBlock ) __OSX_AVAILABLE_STARTING(__MAC_10_11, __IPHONE_9_0);`

Do you know what might be happening?

**Comment by JeremyCooper** [comment]
Solved. Please close.

For reference:
The issue was g++-7.1 was choking on the Objective-C files in the CoreMIDI framework. Was able to compile the library by changing this line (65) in `configure.ac` from:

`AC_PROG_CXX(g++ CC c++ cxx)`
to:
`AC_PROG_CXX(g++ CC g++-7.1 cxx)`

before running
`./autogen.sh`
`./configure`
`make`

**Comment by radarsat1** [comment]
Yup, I just tested on Mac and was about to write the same thing.  It appears there is some Objective-C notation in the header files and no preprocessor switch to avoid it, so maybe CoreMIDI is now incompatible with gcc.  Thanks, Apple.
