### ISSUE TITLE
rtMIDI install problem on Enthought's Canopy 64 bit?

### ISSUE THREAD

**Issue by d-vyd** [thestk/rtmidi#150]
I'm trying to add MIDI (musical instrument digital interface) to a more complex Python install. I was able to get it working with a plain install but was hoping to access all the math and visualization tools in Enthought's Canopy Version: 2.1.6.3665 (64 bit). Has anyone tried this successfully? I'm getting the following error when trying to install rtMIDI:

(User) C:\Users\dle>pip install rtmidi
Collecting rtmidi
  Using cached rtmidi-2.3.2.tar.gz
Installing collected packages: rtmidi
  Running setup.py install for rtmidi ... error
    Complete output from command C:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\dle\\AppData\\Local\\Temp\\pip-build-_31zvv2n\\rtmidi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\dle\AppData\Local\Temp\pip-dsteigpo-record\install-record.txt --single-version-externally-managed --compile:
    C:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\lib\distutils\extension.py:132: UserWarning: Unknown Extension options: 'headers'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\rtmidi
    copying rtmidi\collector.py -> build\lib.win-amd64-3.5\rtmidi
    copying rtmidi\randomout.py -> build\lib.win-amd64-3.5\rtmidi
    copying rtmidi\__init__.py -> build\lib.win-amd64-3.5\rtmidi
    running build_ext
    building 'rtmidi._rtmidi' extension
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    creating build\temp.win-amd64-3.5\Release\cpp_src
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -D__WINDOWS_MM__= -DPK_WINDOWS=1 -IC:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\include -IC:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpcpp_src\RtMidi.cpp /Fobuild\temp.win-amd64-3.5\Release\cpp_src\RtMidi.obj /EHsc
    RtMidi.cpp
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -D__WINDOWS_MM__= -DPK_WINDOWS=1 -IC:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\include -IC:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpcpp_src\MidiMessage.cpp /Fobuild\temp.win-amd64-3.5\Release\cpp_src\MidiMessage.obj /EHsc
    MidiMessage.cpp
    cpp_src\MidiMessage.cpp(1055): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
    cpp_src\MidiMessage.cpp(1057): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -D__WINDOWS_MM__= -DPK_WINDOWS=1 -IC:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\include -IC:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpcpp_src\PyMidiMessage.cpp /Fobuild\temp.win-amd64-3.5\Release\cpp_src\PyMidiMessage.obj /EHsc
    PyMidiMessage.cpp
    cpp_src\PyMidiMessage.cpp(72): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    cpp_src\PyMidiMessage.cpp(87): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -D__WINDOWS_MM__= -DPK_WINDOWS=1 -IC:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\include -IC:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpcpp_src\rtmidimodule.cpp /Fobuild\temp.win-amd64-3.5\Release\cpp_src\rtmidimodule.obj /EHsc
    rtmidimodule.cpp
    cpp_src\rtmidimodule.cpp(50): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
    cpp_src\rtmidimodule.cpp(52): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
    cpp_src\rtmidimodule.cpp(54): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
    cpp_src\rtmidimodule.cpp(56): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
    cpp_src\rtmidimodule.cpp(58): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
    cpp_src\rtmidimodule.cpp(60): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
    cpp_src\rtmidimodule.cpp(62): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
    cpp_src\rtmidimodule.cpp(64): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt\stdio.h(1769): note: see declaration of 'sprintf'
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO "/LIBPATH:C:\Program Files\Microsoft SDKs\Windows    7.1\Lib" /LIBPATH:C:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\libs /LIBPATH:C:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" winmm.lib python34.lib /EXPORT:PyInit__rtmidi build\temp.win-amd64-3.5\Release\cpp_src\RtMidi.obj build\temp.win-amd64-3.5\Release\cpp_src\MidiMessage.obj build\temp.win-amd64-3.5\Release\cpp_src\PyMidiMessage.obj build\temp.win-amd64-3.5\Release\cpp_src\rtmidimodule.obj /OUT:build\lib.win-amd64-3.5\rtmidi\_rtmidi.cp35-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.5\Release\cpp_src\_rtmidi.cp35-win_amd64.lib
    LINK : fatal error LNK1181: cannot open input file 'python34.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1181

    ----------------------------------------
Command "C:\Users\dle\AppData\Local\Enthought\Canopy\edm\envs\User\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\dle\\AppData\\Local\\Temp\\pip-build-_31zvv2n\\rtmidi\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\dle\AppData\Local\Temp\pip-dsteigpo-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\dle\AppData\Local\Temp\pip-build-_31zvv2n\rtmidi\

(User) C:\Users\dle>

**Comment by radarsat1** [comment]
Seems to be a path problem (can't find python34.lib), but in any case I would report the issue to the pypi package author.. https://github.com/patrickkidd/pyrtmidi/issues

**Comment by d-vyd** [comment]
OK. Thank you.
________________________________
