### ISSUE TITLE
Unknown system type for MIDI support!

### ISSUE THREAD

**Issue by MaxRusse11** [thestk/rtmidi#151]
When compiling rtmidi on my i7 laptop, the build is reporting:

checking for MIDI API... configure: error: Unknown system type for MIDI support!

make[1]: *** [Makefile:145: bin/librtmidi-4.dll] Error 1
make[1]: Leaving directory '/c/Source/VCVRack/Rack/dep'
make: *** [Makefile:46: dep] Error 2

the rtmidi tarball is being compiled as a dependency while building VCVRack.

**Comment by radarsat1** [comment]
Inferring you are on Windows from the 'dll'.  Are you using mingw/msys?
Have you tried specifying `--with-winmm`?
Have you tried tweaking configure.ac to debug it?  It's probably something not checking right in `case $host in`.  What is the output of `grep host config.log`?

> - Expected behavior and actual behavior.
> 
> - Steps to reproduce the problem.
> 
> - Specifications like the version of the project, operating system, or hardware.

**Comment by MaxRusse11** [comment]
Yes, this is on Windows 7, building with msys install of mingw gcc 7.2.

I haven't tried any switches on the build, no, as it is being called in as a dependency build.

**Comment by MaxRusse11** [comment]
Project is https://github.com/VCVRack/Rack 0.5

I'm running make dep for the whole project. All other dependencies until this point have succeeded.

**Comment by radarsat1** [comment]
So if you take a quick look at configure.ac you'll see that it only checks for Windows stuff if it sees that $host contains `-mingw32`.  So.  Does $host contain `-mingw32`?  If not, why not?  What do you get when you run `config/config.guess`?

**Comment by MaxRusse11** [comment]
To check - I carry out those steps using autoconf on the rtmidi library separate from the actual dependency build I'm doing for the VCVRack application?

(Sorry - not so accustomed to the compiler and tools for this.)

**Comment by radarsat1** [comment]
Unfortunately I can't answer to VCVRack's build system, but if you compile and install RtMidi alone then you should be able to customise it as you wish.  Also feel free to modify configure.ac if you need to. I would still be interested to know what `config.guess` returns for you.  If it returns anything containing the string "mingw32" then the host should be detected as Windows.  I suggest you change that line in configure.ac if you need to, to match whatever config.guess gives you. (And report it here.)

**Comment by MaxRusse11** [comment]
$ ./config.guess
x86_64-pc-mingw64

added this to my configure.ac : 

`  *-mingw64*)
  # Look for WinMM flag
  AC_ARG_WITH(winmm, [  --with-winmm = choose Windows MultiMedia (MM) API support (windoze only)])
  AS_IF([test "x$with_winmm" == "xyes"], [
    api="$api -D__WINDOWS_MM__"
    AC_MSG_RESULT(using WinMM)
    AC_SUBST( LIBS, [-lwinmm] )])`

Still getting segmentation faults and failing on unknown system type.
[config.log](https://github.com/thestk/rtmidi/files/1621921/config.log)

**Comment by radarsat1** [comment]
Ah, so I've now added mingw64 to the list of known hosts in c5a1c7b0ea79cadcd4532bb03c20713330e32d93.  But I don't know why it's not matching in the case statement for you.  You'll have to debug it.  But if you want to force it, just put

```
AC_MSG_RESULT(using WinMM)
    LIBS="-lwinmm ${LIBS}"
    api="$api -D__WINDOWS_MM__"
```

at the top level and erase the whole `case`, or pass `--with-winmm` to configure.

**Comment by MaxRusse11** [comment]
still get the error when passing --with-winmm

will try the edit.

**Comment by MaxRusse11** [comment]
my system also has ASIO - could I build using that?

**Comment by MaxRusse11** [comment]
[config.log](https://github.com/thestk/rtmidi/files/1628271/config.log)

**Comment by MaxRusse11** [comment]
I've also tried a configure with that latest update. Still getting these issues. Presuming other people have managed to compile on win7 mingw64?

**Comment by radarsat1** [comment]
I still haven't seen any evidence that you've tried overriding the `case` statement to force it to detect your system.  If "host" is not matching "mingw64" after adding that as a case, what is the problem?  You have to try adding some echos and whatnot and figure it out.  Or, like I said, just delete the whole case statement and make it do what you want, which is to configure it for winmm.

to your question, no ASIO is not for MIDI but for audio afaik.

> EDIT = tried removing whole case statement and replacing as suggested, but same error on ./Configure

That's impossible since that error message is emitted by the default of the case statement. If you'd tried removing it, it wouldn't emit the same error.  Are you sure you reran autoconf?

I put a special branch for you here that should do it:  https://github.com/radarsat1/rtmidi/tree/force-winmm

**Comment by radarsat1** [comment]
@MaxRusse11 did you ever figure this out?

**Comment by garyscavone** [comment]
Closing due to lack of response.

**Comment by mawelo** [comment]
Have the same issue during cross compile (ARM):
```
export CXX="arm-linux-gnueabihf-g++"
export CC="arm-linux-gnueabihf-gcc"
./configure --host=arm
...<some output> ...
checking for MIDI API... none
configure: error: No known system type found for MIDI support!
```

**Comment by keinstein** [comment]
> checking for MIDI API... none

Probably you don't have libasound or libjack for arm-linux-gnueabihf installed. At least the corresponding headers are missing. Are they checked during `...<some output> ...`?

**Comment by mawelo** [comment]
> > checking for MIDI API... none
> 
> Probably you don't have libasound or libjack for arm-linux-gnueabihf installed. At least the corresponding headers are missing. Are they checked during `...<some output> ...`?

Thank you Thomas for answering on a closed issue. You are right. I think thats my problem.

**Comment by pierreramiro** [comment]
> > checking for MIDI API... none
> 
> Probably you don't have libasound or libjack for arm-linux-gnueabihf installed. At least the corresponding headers are missing. Are they checked during `...<some output> ...`?

Same error in Ubuntu 20.04. But, solved by typing `sudo apt install libjack1`
