### ISSUE TITLE
SONAME doesn't match version number

### ISSUE THREAD

**Issue by cdr255** [thestk/rtmidi#153]
When rtmidi compiles using the pre-autotoolized tarball provided for version 3.0.0 on the release page it installs librtmidi.so.4.0.0, and not librtmidi.so.3.0.0. (Though I assume this is across all *nixes, I'm using OpenSUSE Tumbleweed x86_64).

Checking the Makefile, it seems this discrepancy is intentional, though other than the header files nothing else is installed. 

Is there a reason the release version shouldn't match the soname version?

**Comment by radarsat1** [comment]
Because the ABI changes at each release. That's the whole point of soname, it tracks ABI changes, it is not the release number.

**Comment by cdr255** [comment]
I see. This helped me learn more about libraries, and better understand why OpenSUSE makes such a big deal about packaging by soname. 

Thank You for taking the time to answer my question.
