### ISSUE TITLE
configure --with-jack not honored

### ISSUE THREAD

**Issue by dvzrv** [thestk/rtmidi#154]
I'm currently moving rtmidi to the Arch Linux repositories.
`configure --with-jack` should lead to the jack backend being included. However, `jack` does not end up in the `Requires` line in `rtmidi.pc`
I hot-fixed this by manually sed'ing it into the file.
[The same problem occurs with rtaudio](https://github.com/thestk/rtaudio/issues/115).

* rtmidi 3.0.0 ([PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rtmidi))

**Comment by radarsat1** [comment]
Please lose if this is fixed in e0f3ebb429f09f2d36838290953a8f0352134f4b

**Comment by dvzrv** [comment]
Yes! Applied my own though, as I didn't understand how to get to that commit.
Basically the `req="$req jack"` was missing.

**Comment by radarsat1** [comment]
My bad I pushed it to my repository but forgot to push to the project repo. It's now on master.

**Comment by dvzrv** [comment]
No worries, added it to the build script for now, until a new version is released.
