### ISSUE TITLE
MidiOutAlsa last events don't get sent, when the RtMidiOut is closed

### ISSUE THREAD

**Issue by jpcima** [thestk/rtmidi#161]
When I call sendMessage on ALSA, there is a delay before it actually gets sent.
If RtMidiOut is destroyed too soon after the sendMessage(), the message never transmits.
In a [MIDI player program](https://github.com/jpcima/fmidi/blob/33b13430b1320ba78e517782f10c8e4c59559b84/programs/midi-play.cc#L298), I want to send final events to restore the state of the instrument after playing, but they don't happen.

Minimal test program: [miditest.cc](https://gist.github.com/jpcima/6e1a3132bc640f66ff15805d90daadff)

If you run this and connect it to gmidimonitor, you may be able to reproduce the problem.

- Steps

1. Run the program, and press enter at each step when prompted.
In the monitor, you see a NoteOn event happen, but not NoteOff.
2. Compile and run again, but uncommenting a 1 second temporization before the end.
You should see the two events.

- Notes

The ALSA api returned 0 on ```snd_seq_drain_output()```, which suggests the event was sent, but in reality it wasn't (yet).
A relevant API may be ```snd_seq_sync_output_queue()``` but I couldn't get anything of it in all I tried.

- Environment
Linux quad 4.15.15-1-ARCH #1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018 x86_64 GNU/Linux
alsa-lib 1.1.5

**Comment by chronopoulos** [comment]
i was not able to reproduce this - i see the Note Off event in both cases. using Linux 4.8.0-53-generic #56~16.04.1-Ubuntu SMP, with libasound2 version 1.1.0 and RtMidi version 3.0.0 (latest release).

what version of RtMidi are you using?

**Comment by radarsat1** [comment]
I'm afraid I also see both events in both cases.
![image](https://user-images.githubusercontent.com/66805/38522856-3d78269c-3c20-11e8-9b9c-09a4b586b512.png)

**Comment by jpcima** [comment]
Just now I find myself unable to reproduce the bug too.
And I realize it's because I was connecting through a2j before. And it was a2j the culprit of the bug all along... Under ordinary conditions it works. So I'm closing this.
