### ISSUE TITLE
Any means to detect a USB Midi controller that has been disconnected

### ISSUE THREAD

**Issue by turgu1** [thestk/rtmidi#169]
First, thanks for giving us this very useful library!

Is there a way to discover that a previously connected USB Midi controller has been disconnected or turned OFF? I'v been trying to use isPortOpen(), getMessage() without any success. The Error Callback is not called either.

I'm using the library with Linux and OSX.

The problem is when the user reconnect the device (or turn it back ON) it is no longer connected to the midi Port previously opened by the application.

Thanks!

Guy

**Comment by sagamusix** [comment]
RtMidi won't give you this; the most feasible solution might be to monitor the OS-specific APIs for hardware changes - if some new USB device is plugged in, check if the previously used MIDI device is available again and re-initialize it.

**Comment by turgu1** [comment]
OK, I found a way using rtMidi: At some interval, my code looks to the list of midi devices using getPortCount() and getPortName(). If the previously opened port is no longer in the list, it close the port and try to reopen it when it is back in the list.

**Comment by turgu1** [comment]
The solution works fine while the code that checks for the port remains in the main application thread. I tried to use it in a pthread and it doesn't work anymore. I suspect ALSA to be the culprit.

**Comment by turgu1** [comment]
Well, a follow on to my last comment: as I'm testing on OSX, it's not with ALSA but with CoreMidi that I can't get an updated list of Midi ports from a pthread. That is showing another point: as the application needs to be portable as much as possible (at least for Linux and OSX), I will keep using the solution I found without using a pthread. I then won't have to take care of the specifics of the underline OS (and the specifics of the device, USB or not).

Somebody with, the proper knowledge of the underneath specialized classes, could implement something that would permit the reconnection with a temporarily lost device in a portable manner, inside RtMidi. I don't know enough about ALSA, CoreMidi ant the other to take the lead.

Thanks again!!

**Comment by radarsat1** [comment]
Unfortunately RtMidi doesn't provide such a polling mechanism, and it would be very hard without a pthread for sure.  I have no idea why such a thing doesn't work from a thread, but perhaps everything midi related needs to be on the same thread.

If any APIs support a callback scheme for this it could be interesting to think about, but without proposals i will close this for now.  On the RtMidi side an exception would probably be the right way to go if disconnection is detected.
