### ISSUE TITLE
issue with installing either via pip or from source. 

### ISSUE THREAD

**Issue by ianhundere** [thestk/rtmidi#177]
- Expected behavior and actual behavior.

attempting to install rtmidi either from the source file or from pip, but given the following error:
```

Installing collected packages: rtmidi
  Running setup.py install for rtmidi ... error
    Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/g0/f3f3h_z54lqbxz_5v2q2hy2w0000gn/T/pip-install-hatvsw3o/rtmidi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/g0/f3f3h_z54lqbxz_5v2q2hy2w0000gn/T/pip-record-_gigowxh/install-record.txt --single-version-externally-managed --compile:
    /anaconda3/lib/python3.5/distutils/extension.py:132: UserWarning: Unknown Extension options: 'headers'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-3.5
    creating build/lib.macosx-10.6-x86_64-3.5/rtmidi
    copying rtmidi/randomout.py -> build/lib.macosx-10.6-x86_64-3.5/rtmidi
    copying rtmidi/collector.py -> build/lib.macosx-10.6-x86_64-3.5/rtmidi
    copying rtmidi/__init__.py -> build/lib.macosx-10.6-x86_64-3.5/rtmidi
    running build_ext
    building 'rtmidi._rtmidi' extension
    creating build/temp.macosx-10.6-x86_64-3.5
    creating build/temp.macosx-10.6-x86_64-3.5/cpp_src`
    /usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -D__MACOSX_CORE__= -I/anaconda3/include/python3.5m -c cpp_src/RtMidi.cpp -o build/temp.macosx-10.6-x86_64-3.5/cpp_src/RtMidi.o -Wno-missing-braces
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from cpp_src/RtMidi.cpp:39:
    cpp_src/RtMidi.h:48:10: fatal error: 'exception' file not found
    #include <exception>
             ^~~~~~~~~~~
    1 warning and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/g0/f3f3h_z54lqbxz_5v2q2hy2w0000gn/T/pip-install-hatvsw3o/rtmidi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/g0/f3f3h_z54lqbxz_5v2q2hy2w0000gn/T/pip-record-_gigowxh/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/g0/f3f3h_z54lqbxz_5v2q2hy2w0000gn/T/pip-install-hatvsw3o/rtmidi/
```
i also tried adding ```extra_compile_args += ['-std=libc++']``` but that didn't help.

- Steps to reproduce the problem.

```pip install rtmidi``` or installing from source file using os x 10.14

- Specifications like the version of the project, operating system, or hardware.

os x mojave(10.14)

**Comment by SpotlightKid** [comment]
You're confusing the [Python package rtmidi](https://pypi.org/project/rtmidi/), with the C++ library **RtMidi** (this repo). The former is a Python binding (one of several existing) for the latter.

Unfortunately there are at least three projects providing Python bindings for RtMidi and they're all named similarly. I maintain [python-rtmidi](https://github.com/SpotlightKid/python-rtmidi) (which you [already know](https://github.com/SpotlightKid/python-rtmidi/issues/35)), then there's [rtmidi-python](https://pypi.org/project/rtmidi-python/), and there's [rtmidi](https://pypi.org/project/rtmidi/), which I already linked in the first paragraph.

What adds to the confusion, that most (all?) of these bindings include the actual source files of RtMidi (`RtMidi.h` and `RtMidi.cpp`) in their repos and distribution packages and these may lag behind the state of the sources in the official (this) repo.

**Comment by fornof** [comment]
https://github.com/mido/mido/issues/171#issuecomment-485145344

**Comment by SpotlightKid** [comment]
The person reporting this issue was trying to install the Python package `rtmidi`, **not** `python-rtmidi`, which the `mido` issue you linked is about. The issue reported there was already reported in the `python-rtmidi` repo with the same solution: https://github.com/SpotlightKid/python-rtmidi/issues/35

But, again, this issue is about a confusion between RtMidi and the different Python bindings.

**Comment by duanev** [comment]
Do you a preference/opinion on which python binding project best represents the C++ classes (or performs best)?  We should work to narrow the options  :)
