### ISSUE TITLE
Incorrect return value from RtMidiIn::getPortName in qmidiin.exe

### ISSUE THREAD

**Issue by shintamainjp** [thestk/rtmidi#183]
# Environments

* Release v3.0.0
* Visual Studio 2013 Professional

# Expected behavior and actual behavior.

## Reference output from midiprobe.exe

In my environment, it has two midi input devices as you can see the output of midiprobe.exe.

> Compiled APIs:
>   Windows MultiMedia
> 
> Current input API: Windows MultiMedia
> 
> There are 2 MIDI input sources available.
>   Input Port #1: QUAD-CAPTURE 0
>   Input Port #2: nanoPAD2 1
> 
> Current output API: Windows MultiMedia
> 
> There are 3 MIDI output ports available.
>   Output Port #1: Microsoft GS Wavetable Synth 0
>   Output Port #2: QUAD-CAPTURE 1
>   Output Port #3: nanoPAD2 2
> 

When I use qmidiin.exe for the second device named 'nanoPAD2', the returned device name is still pointing device index number 0 however the behavior is correct. (I can see the MIDI events from the target device 1.) Probably only the return name is incorrect I think.

> qmidiin.exe 1
> Reading MIDI from port QUAD-CAPTURE 0 ... quit with Ctrl-C.
> Byte 0 = 144, Byte 1 = 37, Byte 2 = 76, stamp = 0
> Byte 0 = 128, Byte 1 = 37, Byte 2 = 64, stamp = 0.053

## Other arguments

> qmidiin.exe 0
> Reading MIDI from port QUAD-CAPTURE 0 ... quit with Ctrl-C.

> qmidiin.exe 2
> Invalid port specifier!
> 
> usage: qmidiin <port>
>     where port = the device to use (default = 0).

**Comment by shintamainjp** [comment]
Sorry, I forgot writing the run time environment.
I am running the qmidiin.exe on Windows 10 Home Version 1803 (OS Build 17134.472)

**Comment by radarsat1** [comment]
I can see how it's confusing but midiprobe is printing device number `i+1` so there's a +1 offset.  The other number at the end of the line is [appended specifically](https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L2642) by RtMidi's Windows MM API implementation, it was a hack to ensure port names were unique under some circumstance or other that I can't remember...

Anyways you are right that what is printed by midiprobe is not what qmidiin expects.

**Comment by garyscavone** [comment]
I just fixed this in 4d87f30.
