### ISSUE TITLE
Homebrew formula missing rtmidi.pc

### ISSUE THREAD

**Issue by chao-mu** [thestk/rtmidi#184]
The homebrew formula for rtmidi appears to not install a rtmidi.pc (pkg-config) file. This means that people who rely on pkg-config to build their projects will have difficulty distributing their project with rtmidi as a dependency. 

Here is a link to the formula https://github.com/Homebrew/homebrew-core/blob/master/Formula/rtmidi.rb

which I got from the formula's page https://formulae.brew.sh/formula/rtmidi

**Comment by radarsat1** [comment]
The homebrew formula is not maintained here.  Have you tried filing it as an issue at homebrew-core?

**Comment by chao-mu** [comment]
Sorry about that. I wasn't quite sure where to post. Thank you!

**Comment by radarsat1** [comment]
No worries.
