### ISSUE TITLE
.pc file makes all users to link with Jack

### ISSUE THREAD

**Issue by yurivict** [thestk/rtmidi#204]
```
$ pkg-config --libs rtmidi
-L/usr/local/lib -lrtmidi -ljack -pthread 
```

```-ljack``` isn't needed when shared libraries are used.

```
$ pkg info -l rtmidi
rtmidi-4.0.0:
	/usr/local/include/rtmidi/RtMidi.h
	/usr/local/include/rtmidi/rtmidi_c.h
	/usr/local/lib/librtmidi.so
	/usr/local/lib/librtmidi.so.5
	/usr/local/lib/librtmidi.so.5.0.0
	/usr/local/libdata/pkgconfig/rtmidi.pc
```

**Comment by radarsat1** [comment]
True, I guess needed only if `--disable-shared`.  Might take a bit of work to fix, marking as bug to remind me.

**Comment by radarsat1** [comment]
Okay it turned out to be rather easy.  Just need to change "Requires:" to "Requires.private", then the correct libs can be requested by passing `--static` to pkg-config.
