### ISSUE TITLE
rtmidi does not provide the include path to RtMidi.h

### ISSUE THREAD

**Issue by lubkoll** [thestk/rtmidi#207]
Using RtMidi's cmake target RtMidi::rtmidi in target_link_libraries does provide the library but not the include path for RtMidi.h as the generator expressions for 'target_include_directories(rtmidi ...)' are private.

A fix is provided in this pull-request: https://github.com/thestk/rtmidi/pull/206

**Comment by radarsat1** [comment]
Thanks, this has now been merged.
