### ISSUE TITLE
Add repology badge to README

### ISSUE THREAD

**Issue by luzpaz** [thestk/rtmidi#209]
### Summary
A way for users to see what downstream repositories carry rtmidi

### Proposed design
The full badge looks like so:  
[![Packaging status](https://repology.org/badge/vertical-allrepos/rtmidi.svg?header=rtmidi)](https://repology.org/project/rtmidi/versions)  

but since it take up a lot of room it can be simply added as a single badge such as:

[![Packaging status](https://repology.org/badge/tiny-repos/rtmidi.svg)](https://repology.org/project/rtmidi/versions)

**Comment by radarsat1** [comment]
I don't think we want to litter our README with lots of badges, thanks anyway.
