### ISSUE TITLE
[Clang build] Warnings on enum

### ISSUE THREAD

**Issue by suamor** [thestk/rtmidi#217]
The maintainers / developers of RtMidi favour pull requests over issues. We generally do not have access to all the supported platforms to attempt to verify a reported problem. It will help the entire RtMidi community if you can debug a problem you are reporting and suggest a way to fix it yourself.

-> Tried this but github refuses me to upload my changes. Documentation states that I need write access to repository (which I do not want, I simply want to upload a patch-set). Please add some documentation if there is another way.

- Expected behavior and actual behavior.
Method getApiName and getApiDisplayName build without issues using Clang compiler (C++14 to my knowledge is default)

- Steps to reproduce the problem.
Build RtMidi with Clang compiler (I used clang-9 and clang-10) using cmake.

- Specifications like the version of the project, operating system, or hardware. 
RtMidi from master build today, originally occurred on Canorus 0.8 Milestone (currently master)

Solution:
Either remove check against 0 or use a dedicated enum value for it. Use static_cast if you still need to support old C++ compilers. Please let me know what you prefer I can provide patch-set.

**Comment by radarsat1** [comment]
I noticed this in Travis the other day, haven't gotten to fixing it yet, thanks for the report! I'll close this asap.

**Comment by radarsat1** [comment]
Hm so far I haven't been able to reproduce in a docker container running debian sid.. i tried the gcc-10, clang-10, and clang-9 packages, but none of them give me any warnings.

@suamor can you tell me exactly what your configuration is (OS, if mac, homebrew or ports, etc..) and paste an example of the warning or error you get?

**Comment by radarsat1** [comment]
If I understood from your description, maybe this branch fixes it?

**Comment by radarsat1** [comment]
https://github.com/thestk/rtmidi/tree/api-enum-warning

**Comment by suamor** [comment]
Yes, that would fix it. I'm on Ubuntu 20.04 LTS with clang-10 and clang-9. I think I started out with clang-10 and fixed a few warnings there. Build was done in QtCreator. We are using CMake for building rtmidi (but use our own CMakeLists.txt file).
The warning was fixed with some pull request https://github.com/canorusmusic/canorus/pull/164

**Comment by suamor** [comment]
Regarding pull request: I noticed that a fork can be used for creating pull request. I'm hesistant on using that method because according to the github documentation it create a copy of the repository and simple pointers to the (remote branch) files like on branch creation.

**Comment by radarsat1** [comment]
> Yes, that would fix it.

I have tried with ubuntu 20.04 and debian sid docker images but i seem unable to get the warning you are talking about.  I have tried clang-9, clang-10, g++-10, building with `-Wall -Wextra -Werror`, no warnings.  That said it's such a minimal change that I don't think it matters much, i'll go ahead and merge it if it fixes something, but can you actually test it and tell me if the warning is eliminated?  Otherwise I am blind.

> Regarding pull request: I noticed that a fork can be used for creating pull request.

This is just how github works.  I also wish they had a lighter-weight way to submit contributions, but forks are how they decided to go for some reason.  If it's really distastful to make a PR you can for example paste a diff here, or send it by email.
