### ISSUE TITLE
Optional midiOutReset in `MidiOutWinMM :: closePort`.

### ISSUE THREAD

**Issue by sintech** [thestk/rtmidi#222]
Please consider making `midiOutReset` call optional in `MidiOutWinMM :: closePort`.
Because currently it sends 0x7b (if any note was ON) and 0x79 "Reset All Controllers" (to all 16 channels) CC messages at port closure, which is undesirable in some Use cases.
https://github.com/thestk/rtmidi/blob/d4972bcfaacfbdbb254b5d5546bd6b369e4f5f21/RtMidi.cpp#L2851

**Comment by SpotlightKid** [comment]
Oh, that is where this is coming from? I had several bug reports related to this from Windows users of `python-rtmidi` and just assumed WinMM was always doing this, when a port si closed. Good to know this could be turned off.

**Comment by sagamusix** [comment]
This change is available in RtMidi 5.0.0. I guess the issue should be closed.
