### ISSUE TITLE
Unable to build a minimal C API code

### ISSUE THREAD

**Issue by 6r1d** [thestk/rtmidi#229]
Hello. I want to learn how to use RtMIDI C API.

I don't know how to continue, because I am stuck with several issues. If I am using a default Ubuntu 18.04.5 LTS / Bionic package version (`librtmidi-dev/bionic 3.0.0~ds1-2 amd64`), this is what I see.

```
In file included from main.c:18:0:
/usr/include/rtmidi/rtmidi_c.h:31:9: error: unknown type name ‘RtMidiWrapper’
 typedef RtMidiWrapper* RtMidiPtr;
         ^~~~~~~~~~~~~
/usr/include/rtmidi/rtmidi_c.h:34:9: error: unknown type name ‘RtMidiWrapper’
 typedef RtMidiWrapper* RtMidiInPtr;
         ^~~~~~~~~~~~~
/usr/include/rtmidi/rtmidi_c.h:37:9: error: unknown type name ‘RtMidiWrapper’
 typedef RtMidiWrapper* RtMidiOutPtr;
         ^~~~~~~~~~~~~
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

with this being my code

```c
#include <stdio.h>
#include "rtmidi_c.h"

struct RtMidiWrapper *midiin;

int main() {
  midiin = rtmidi_in_create_default();
  return 0;
}
```

I thought this is the way to go after finding [this source](https://github.com/alexheinrich/waveshaping/blob/master/mid.c). I understand it's mostly unrelated, but I found no examples for C.

And this command to build it:

```
cc -Wall main.c -o main -I /usr/include/rtmidi -lpthread
```

I have thought that my RtMIDI might be rather old and tried to use CMake and build / install it after removing a default package. I can't, sadly; this is what I see:

```
-- Installing: /usr/local/lib/librtmidi.so.5.0.0
-- Installing: /usr/local/lib/librtmidi.so.5
-- Up-to-date: /usr/local/lib/librtmidi.so
-- Installing: /usr/local/include/RtMidi.h
-- Installing: /usr/local/share/rtmidi/RtMidiConfig.cmake
-- Installing: /usr/local/share/rtmidi/RtMidiTargets.cmake
-- Installing: /usr/local/share/rtmidi/RtMidiTargets-noconfig.cmake
-- Installing: /usr/local/lib/pkgconfig/rtmidi.pc
```

Neither `rtmidi_c.h` nor `rtmidi_c.cpp` are available after installation. How can I configure CMake so I can use enable C API support? Is C API currently supported?

Thanks.

**Comment by radarsat1** [comment]
* A (very minimal) test for the C API has been added in PR #256. 
* The file `rtmidi_c.h` is now properly installed.

Regarding availability on Linux distributions, this will of course not be available until a new release happens and packagers package and upload it.

I'll close for now, but please re-open if you still have difficulties.
