### ISSUE TITLE
iOS: support convert audio to midi？

### ISSUE THREAD

**Issue by norman93sun** [thestk/rtmidi#233]
Support convert audio to midi on iOS（objectc）？

**Comment by keinstein** [comment]
You can any software that supports MIDI output. Either you open a virtual input port in RtMidi and connect your software to that or your software supports virtual output ports and you can connect your RtMidi application to that port.

Note: Converting Audio to MIDI is a non-trivial task. Research has been done on this topic for decades. I don't know whether there is a realtime multitimbral polyphonic approach that can deal with a full symphonic orchestra. In my opinion it should be updated separatedly from a library like RtMidi which is intended to develop slowly.
