### ISSUE TITLE
Send message to MIDI port

### ISSUE THREAD

**Issue by demetera** [thestk/rtmidi#235]
When I send message to MIDI port and immediately stop the program, message won't send:

```
RtMidiOut *midiout = new RtMidiOut();
vector <unsigned char> msg;
msg = {176, 74, 0}; //tried also msg.push_back to add unsigned chars to vector
midiout->sendMessage(&msg);
```

Message isn't delivered to MIDI port (software or hardware one)
when I add:
usleep (100000); from unistd.h or more delay, message got delivered.

- Qt 5 project compiled with gcc 10.2.0 , with RtMidi.h and RtMidi.cpp from original tree
- Linux Manjaro 5.9.16
- JACK 2 1.9.17-2

**Comment by SpotlightKid** [comment]
Where is `openPort()` and do you close the port with `closePort()`? Post  a full minimal example, please.

**Comment by demetera** [comment]
Sorry. Forgot to include full example.
This is not working for me (excepting line with delay):

```
RtMidiOut *midiout = new RtMidiOut();
vector <unsigned char> msg;
midiout->openPort(0);
msg = {176, 74, 0};
midiout->sendMessage(&msg);
//usleep(100000); // or for instance sleep(1); - message delivered in this case
midiout->closePort();
delete midiout;
```

**Comment by demetera** [comment]
It's also happens, when I want to send message to turn note off:

```
RtMidiOut *midiout = new RtMidiOut();
vector <unsigned char> msg;
midiout->openPort(0);
msg = {144 64, 127};
midiout->sendMessage(&msg);
sleep(1); //note playing for 1 second
msg = {128, 66, 0};
midiout->sendMessage(&msg); //Message isn't delivered and keeps playing unless I won't put at least 0.1 sec pause
midiout->closePort();
delete midiout;
```

**Comment by SpotlightKid** [comment]
That's not a *full* example (one that one can compile out of the box).

Anyway, you need to compile with `-DHAVE_SEMAPHORE` an `-lpthread`, e.g.

    g++ -Wall -DHAVE_SEMAPHORE -DJACK_HAS_PORT_RENAME -D__UNIX_JACK__ -o test test.cpp  RtMidi.cpp -ljack -lpthread

**Comment by demetera** [comment]
Thank you! Problem was solved with compiling this way.
Also, I don't warning about Jack anymore (jack port rename).
