### ISSUE TITLE
delta time.

### ISSUE THREAD

**Issue by spyroot** [thestk/rtmidi#241]
Hi Folks,

First of all, thank you very much for the library and all examples.   
You don't have a category for request information.  It is a bit unclear from the documentation 
how exactly you are calculating delta time. I understand it double but not sure about what event used to calculate delta.
Do you timestamp every Incomming MIDI message?  

I'm trying to record MIDI send by DAW and do a unit test and compare the original midi 
playback with what I recorder,  by my timing significantly different in result MIDI file I create.

DAW also sends a clock message during MIDI play. 
Do I need to re-adjust delta-time based on the previous clock message received and re-calculate?

Thank you very much

**Comment by garyscavone** [comment]
It seems to depend on the API. For CoreMIDI and Jack, it calculates the time between reception of messages using the host time. For ALSA and WinMM, it uses the times that come with each message. In all cases, it is calculating delta times ... the time between the current and last event. If you need to sync with some system time, then you would need to keep adding delta times to your starting time.

**Comment by spyroot** [comment]
Thank you very,   yes I was able to correctly calculate the time track the real-time clock, and send seq back to a DAW.
