### ISSUE TITLE
makefile fixes

### ISSUE THREAD

**Issue by oskude** [thestk/rtmidi#25]
couple Makefile.in fixes for a cleaner build on linux

[dir-destdir-rterror.patch](https://gist.github.com/11347478)

* remove RtError.h - "[embedded directly in RtMidi.h](http://www.music.mcgill.ca/~gary/rtmidi/index.html#whatsnew)"
* tell `install` to create missing directories - e.g. fakeroot
* use DESTDIR instead of PREFIX for `make install` - https://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Comment by garyscavone** [comment]
Hopefully fixed with recent build updates.
