### ISSUE TITLE
New release including MIDIClientRef singleton

### ISSUE THREAD

**Issue by MartinDelille** [thestk/rtmidi#251]
Would you mind creating a new release including the [MIDIClientRef singleton PR](https://github.com/thestk/rtmidi/pull/220) with solved my issue with random midi initialization error?

I'm currently working on a conan recipe for rtmidi: https://github.com/conan-io/conan-center-index/pull/6307

I would be happy to use this recipe with fix (otherwise I will have to add the patch to the recipe).

**Comment by MartinDelille** [comment]
The formula for RtMidi has been merged to the conan center index: https://github.com/conan-io/conan-center-index/pull/6307

Would you mind releasing a 4.0.1 including the latest commits?

**Comment by MartinDelille** [comment]
Hi @radarsat1 ! I see a lot of activity on the repository these last days. Do you plan to release a new version?

**Comment by garyscavone** [comment]
That is the goal, though it might not happen until next month.

**Comment by MartinDelille** [comment]
Thanks for the new release! I will update the conan formula  ASAP!

**Comment by MartinDelille** [comment]
The conan recipe has been merged! https://github.com/conan-io/conan-center-index/pull/8094
