### ISSUE TITLE
Reset/set MIDI channel to some value

### ISSUE THREAD

**Issue by vtushevskiy** [thestk/rtmidi#270]
Is it possible to send a message from computer to MIDI device to set certain channel to some value or just reset it to 0?

**Comment by keinstein** [comment]
BTW. The official documents can be download on the [official website of the MIDI Association](https://www.midi.org/specifications/midi1-specifications) free of charge (Registration required). Its always a good decision to be compliant, so that your idea also works with other hard- or software.
