### ISSUE TITLE
Windows: Test applications for receiving messages don't work

### ISSUE THREAD

**Issue by edgarfauquier** [thestk/rtmidi#273]
Hello!

I'm trying the "test" applications on Windows 10.

My idea is to start _cmidiin_ listening to a desired port, then start _midiout_ to send messages to the same port, and i would expect to see the messages being received in _cmidiin_, but unfortunately i don't see such messages being received. I have tried both _cmidiin_ and _qmidiin_, but none of them works.

I have proved (by using external applications) that messages are being sent correctly from _midiout_.

Any ideas?

Thank you very much!

**Comment by jg-854** [comment]
I notice you have closed this issue - please may you explain the problem and how you  solved it?

**Comment by edgarfauquier** [comment]
Hey!

I'm not too sure I have solved it in fact.

Just realized that after installing _loopMIDI_ and creating a virtual port, then apps are able to send and receive messages through it. Originally I was using the port created by rtpMIDI.

Am I missing anything?

Best regards!

**Comment by keinstein** [comment]
rtpMIDI just makes two separate virtual MIDI wires between your lan and MIDI ports.  Did you connect a loopback rtpMIDI client? If not, you experience expected behaviour.
