### ISSUE TITLE
ks.h and ksmedia.h should not be included in RtMidi

### ISSUE THREAD

**Issue by keinstein** [thestk/rtmidi#28]
The two files are part of the Windows API and should not be provided with RtMidi. Overriding the system supplied version with another one will cause problems in the long run.

You should also be aware that DLLs are only linked at runtime. There exists always some glue code between the DLL and the software so that the Windows ABI does not 
necessarily have to comply with the binary interface of the API headers.

**Comment by garyscavone** [comment]
KS code is now in a different branch and not really working ... needs fixing.
