### ISSUE TITLE
In/Out devices swapped around for Novation Launchpad Mini MK3

### ISSUE THREAD

**Issue by rix0rrr** [thestk/rtmidi#290]
I'm on MacOS (10.15), using RtMidi with a Novation Launchpad Mini MK3.

Running the following program:

```cpp
int main(void) {
    RtMidiIn in;

    for (int i = 0; i < in.getPortCount(); i++) {
        std::cout << in.getPortName(i) << std::endl;
    }

    return 0;
}
```

Note I'm using `RtMidiIn`, but the output is:

```
Launchpad Mini MK3 LPMiniMK3 DAW Out
Launchpad Mini MK3 LPMiniMK3 MIDI Out
```

For `RtMidiOut`, the names are reversed (I see the `In` devices).

I wouldn't even know where to start figuring out how this is happening, but I can't seem to properly interface with my device and I wonder if this might be the reason.

Testing this against HEAD (454e1ce).

**Comment by garyscavone** [comment]
RtMidiIn is seeing two sources of MIDI data, one called DAW Out and the other called MIDI Out. Your device will send data out those ports and RtMidiIn can receive data from those ports.

**Comment by rix0rrr** [comment]
You are saying the MIDI devices are named from the perspective of the instrument, not the perspective of the computer?

**Comment by rix0rrr** [comment]
Okidoke. Thanks for the info!
