### ISSUE TITLE
Correct way of specifying channel?

### ISSUE THREAD

**Issue by opoloko** [thestk/rtmidi#294]
Hi

I tried looking into examples and repo, but I can’t find anything showing what would be the best and simpler way to set a specific midi channel when using a vector to compose the message to send?

Any hint or example? It’s all working but I can’t find an easy way/example of sending to different midi channel.

**Comment by insolace** [comment]
Here's some pseudocode, you'd do better to make a function that handles all of the various message formatting, number of data bytes, etc, but this will give you a start.

Check out this table if you need a primer on midi messaging:

http://ericbateman.com/midi/table1.html

// code

unsigned char status, channel, data1, data2;

status = MIDI_NOTE_ON; // this is 0x90, you should have all status bytes defined somewhere

channel = 0; // channels are zero indexed

data1 = 64; // middle C
data2 = 127; // velocity

// this could be adapted to a function
message[0] = status | channel;
message[1] = data1;
message[2] = data2;
midiOut->sendMessage (&message);

**Comment by opoloko** [comment]
Thanks all good, understood and implemented, your reply was very useful!
