### ISSUE TITLE
Need help on the RtMidi library implementation in Visual Studio Code

### ISSUE THREAD

**Issue by ruiseixasm** [thestk/rtmidi#302]
Hi, I'm trying to use the library RtMidi and after being able to include the library path I'm still having errors despite being following the [web page instructions](https://www.music.mcgill.ca/~gary/rtmidi/) of the library.

This is the code I'm trying to run:

```
#include "..\..\includes\computer\rtmidi\RtMidi.h"

int main()
{
    try {
    RtMidiIn midiin;
    } catch (RtMidiError &error) {
        // Handle the exception here
        error.printMessage();
    }
    return 0;
}
```

To make sure the VSC compiler is finding the include path, I first try it by commenting the include line, and besides the intellisense identified the errors this was the compiler output:

```
[Running] cd "c:\Users\rui\Documents\GitHub\libraries_implementations\projects\midi\" && g++ main.cpp -o main && "c:\Users\rui\Documents\GitHub\libraries_implementations\projects\midi\"main
main.cpp: In function 'int main()':
main.cpp:12:3: error: 'RtMidiIn' was not declared in this scope
   RtMidiIn midiin;
   ^~~~~~~~
main.cpp:13:11: error: 'RtMidiError' does not name a type
  } catch (RtMidiError &error) {
           ^~~~~~~~~~~
main.cpp:15:3: error: 'error' was not declared in this scope
   error.printMessage();
   ^~~~~

[Done] exited with code=1 in 0.127 seconds
```

Then I uncommented the first line with the include statement, all the intellisense errors disappeared and after I try to compile it I got this from the compiler:

```
[Running] cd "c:\Users\rui\Documents\GitHub\libraries_implementations\projects\midi\" && g++ main.cpp -o main && "c:\Users\rui\Documents\GitHub\libraries_implementations\projects\midi\"main
C:\Users\rui\AppData\Local\Temp\cc46TOPo.o:main.cpp:(.text+0x59): undefined reference to `RtMidiIn::RtMidiIn(RtMidi::Api, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int)'
C:\Users\rui\AppData\Local\Temp\cc46TOPo.o:main.cpp:(.text+0x7a): undefined reference to `RtMidiIn::~RtMidiIn()'
collect2.exe: error: ld returned 1 exit status

[Done] exited with code=1 in 0.653 seconds
```

So, I'm still getting compiler errors despite following all the instructions and despite of the very simple code program.

Can you help me on this one? Thanks.

**Comment by shemeshg** [comment]
I'm not of the RtMidi support group, but I'm pretty sure you can not 
`#include "..\..\includes\computer\rtmidi\RtMidi.h"`

You should `#include "RtMidi.h"` and

It is ether you 
1. in your .zshrc - If installed with brew or aptget
```
export C_INCLUDE_PATH=/usr/local/include
export CPLUS_INCLUDE_PATH=/usr/local/include
```
2. Put the RtMidi.h and RtMidi.cpp files under your folders root.
3. Use CMAKE sub_folders, as a static/dynamic library (Under Workspace root also)
4. vcpkg (Not sure RtMidi distributed in vcpkg)
