### ISSUE TITLE
Linker errors with compiled libraries on OS X

### ISSUE THREAD

**Issue by birarda** [thestk/rtmidi#32]
On OS X 10.9.3 I'm having issues linking the compiled rtmidi libraries, static or dynamic.

Both cause me to get a linker error no matter what API function I call from my application.

I've defined __MACOSX_CORE__.

```
Undefined symbols for architecture x86_64:
  "RtMidi::getCompiledApi(std::vector<RtMidi::Api, std::allocator<RtMidi::Api> >&)", referenced from:
      Application::Application(int&, char**, QElapsedTimer&) in Application.o
```

**Comment by drewish** [comment]
@garyscavone I think this can be closed.
