### ISSUE TITLE
Can't send over RTMIDI_API_WINDOWS_MM

### ISSUE THREAD

**Issue by ClosetMonkey** [thestk/rtmidi#327]
I am using RtMidi 6.0.0 on Windows 11. I am able to send and receive without a problem when using RTMIDI_API_WINDOWS_UWP but as soon as I use RTMIDI_API_WINDOWS_MM it is unable to send, only receive. I am testing using an APC40 device.

**Comment by Paul-Dempsey** [comment]
I have another application that sends and receives fine with WinMM on Windows 11 (VCV Rack). Without more details of exactly where rtmidi is going wrong for you, this isn't an actionable report. You'll want to do some debugging to see what the issue is in more detail.

**Comment by ClosetMonkey** [comment]
Thank you for your response. It was user error 😬
