### ISSUE TITLE
Different MIDI device names on different platforms

### ISSUE THREAD

**Issue by MeestorX** [thestk/rtmidi#334]
Port names seem to be returned differently on each platform.

On OSX and Windows I have:
`'USB Uno MIDI Interface'`

On Linux I get:
`'USB Uno MIDI Interface:USB Uno MIDI Interface MIDI 1 24:0'`

What are the values to the right of the `:` ?

I got the impression that issue [#54](https://github.com/thestk/rtmidi/issues/54) might have addressed this in some way?

**Comment by insolace** [comment]
These are the port names as reported by the OS. For multiport devices it gets even worse, where windows ignores the descriptors but MacOS does not.I’ve been told by the ALSA folks that they updated this in a more recent kernel to at least include the USB descriptor strings, but those numbers on the right are the ALSA ports. No matter what, you’re going to have to do some platform specific string comparisons.On Mar 8, 2024, at 9:41 AM, Andrew Broughton ***@***.***> wrote:﻿
Port names seem to be returned differently on each platform.
On OSX and Windows I have:
'USB Uno MIDI Interface'
On Linux I get:
'USB Uno MIDI Interface:USB Uno MIDI Interface MIDI 1 24:0'
What are the values to the right of the : ?
I got the impression that issue #54 might have addressed this in some way?
