### ISSUE TITLE
Is it possible to play a sound though the audio driver?

### ISSUE THREAD

**Issue by MaikKlein** [thestk/rtmidi#37]
I am currently on linux and I am playing around with rtmidi. Now I was able to play a sound though my digital piano but I am wondering if I can also output the sound though my speakers?

When my digital piano is not connected I still get one device with getPortCount(); I assumed that is my audio driver. The device name is Midi Through:0 which is somewhat strange.

But I don't hear any sound and I am not sure if that is the intended behavior. Can I play midi sounds though my audio driver with rtmidi? Or do I need another library for this?

**Comment by allan-simon** [comment]
you can using timidity (but the project is not supported anymore)

**Comment by SpotlightKid** [comment]
Use the fluidsynth program or library with a proper soundfont.
