### ISSUE TITLE
When receiving MIDI clock on MIDI IN, deltatime varies when MIDI OUT is being used

### ISSUE THREAD

**Issue by sinosoidal** [thestk/rtmidi#38]
Hi,

I'm facing a problem which i'm not certain about who's fault is.

I'm using RtMidi to receive and send MIDI. My app runs on Windows and Mac. The app receives the MIDI clock on MIDI In and calculates the BPM. It relies on deltatime to do it. On the other hand, commands are sent via MIDI out to the app. Everything perfect on Mac. 

On Window however, everytime I start send MIDI out messages, the deltatime of the midi in callback is affected and the result is a bad calculation of the BPM everytime commands are being sent. This doesn't make sense. Is it supposed to be related? I'm using LoopBe as MIDI driver. 

I would definitely love to hear your opinon here. 

Regards,

Nuno

**Comment by napent** [comment]
Hi  sinosoidal, can you provide me some direction for getting synced by midi clock in STK?

**Comment by radarsat1** [comment]
I haven't played with clocks in a while so I wrote a little example program, you can find it in tests.  Tested on Linux only, ymmv.

https://github.com/thestk/rtmidi/blob/master/tests/midiclock.cpp

**Comment by radarsat1** [comment]
![Image of midiclock test running](http://i.imgur.com/1JU7Ckw.png)
