### ISSUE TITLE
change pkg-config name to rtmidi

### ISSUE THREAD

**Issue by albfan** [thestk/rtmidi#41]
I have found many people configure autotools with 

```
PKG_CHECK_MODULES(RTMIDI, rtmidi)
```

https://gist.github.com/nils-werner/4d1e935b474f525835b5

But I can find any repo with such configuration. Installing from repo it is librtmidi. Is there any plans to change it or any branch (stable/unstable) with that changes?

**Comment by garyscavone** [comment]
Old ... and the description isn't sufficient to understand the problem.

**Comment by albfan** [comment]
It was about this line https://github.com/thestk/rtmidi/blob/master/rtmidi.pc.in#L6

From librtmidi to rtmidi
