### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by MartinDelille** [thestk/rtmidi#45]
After installing *autoconf* I run *./configure* and get the following error:

    configure: error: cannot find install-sh, install.sh, or shtool in config "."/config

Any idea?

**Comment by Ghopper21** [comment]
I got the same error on a Mac with latest commit, even after doing `brew install shtool`. Checked out tag 2.1.0 and it works.

**Comment by SpotlightKid** [comment]
To get all the autoconf/automake stuff, I have to run these commands in the order given:

```
libtoolize
aclocal
automake --add-missing
autoconf
```

I put these into an `autogen.sh` file together followed by a `./configure` call.

**Comment by MartinDelille** [comment]
Thanks it worked for me!
