### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by MartinDelille** [thestk/rtmidi#47]
Since the API change (particulary in this commit 2c7a6664d69ed39d9d1d4312231c064e9b1549dd), would it be possible to release a new version?

**Comment by MartinDelille** [comment]
@garyscavone Is there any release in view?

**Comment by garyscavone** [comment]
Yes � hopefully within the next week.

�gary

**Comment by MartinDelille** [comment]
:+1:

**Comment by SpotlightKid** [comment]
Yeah!

**Comment by garyscavone** [comment]
The new release will happen today or tomorrow.

**Comment by MartinDelille** [comment]
ok I'll update the [brew formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/rtmidi.rb) then!
