### ISSUE TITLE
error running autoconf

### ISSUE THREAD

**Issue by emarin** [thestk/rtmidi#56]
Hi,
When trying to run autoconf on a debian machine I get the following errors : 
`configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:14: error: possibly undefined macro: AM_PROG_AR`

I am running autoconf v 2.69

Thanks

**Comment by emarin** [comment]
I didn't see that previous issue was solving my problem, until the following command which returns : 
`> automake --add-missing
Makefile.am:3: variable `%C%_librtmidi_la_SOURCES' is defined but no program or
Makefile.am:3: library has `%C%_librtmidi_la' as canonical name (possible typo)
Makefile.am:2: variable `%C%_librtmidi_la_LDFLAGS' is defined but no program or
Makefile.am:2: library has `%C%_librtmidi_la' as canonical name (possible typo)`

This seems to cause Makefile creation to fail

Thanks

**Comment by scryver** [comment]
Had the same problem with configure.ac. I solved it by running 'autoreconf --install' before the autoconf command. I was apparently missing some components.
