### ISSUE TITLE
ALSA reports wrong port count after ports have been opened

### ISSUE THREAD

**Issue by ZioGuido** [thestk/rtmidi#72]
RtMidiIn::getPortCount() with ALSA: if I'm invoking this method _after_ some Midi In and Out ports are already open, rather than only the actual number of existing Midi inputs, this function returns the total sum of the exsisting Midi In ports (whether opened or not) plus the number of opened (and only opened) Midi Out ports.

In my case, I have 5 Midi inputs and 5 Midi outputs, my application opens all inputs and only 2 outputs. If I call RtMidiIn::getPortCount() after all ports have been successfully open and working, I get 7 (5 + 2) instead of 5.

I'm doing this because I'm polling in order to check whether a Midi device has been added or removed, in which case the program should close all ports and reopen them. Since I need to open all Midi Inputs and only the specified two Midi outputs, I'm checking the number of inputs.

The port count is reported correctly if no ports are open. And this issue only applies to ALSA. Everything is ok with Windows.

**Comment by atsushieno** [comment]
I believe I have a repro for this issue:

	#include "RtMidi.h"
	#include <stdio.h>
	#include <iostream>
	#include <vector>

	using namespace std;

	int main ()
	{
		vector<RtMidi::Api> apis;
		RtMidi::getCompiledApi (apis);
		cout << apis.size() << endl;
		RtMidiIn *input = new RtMidiIn (apis[0], "input");
		RtMidiOut *output = new RtMidiOut (apis[0], "output");
		cout << input->getPortCount () << " " << output->getPortCount () << endl;
		output->openPort (0, "port0");
		cout << input->getPortCount () << " " << output->getPortCount () << endl;

		output->closePort ();

		delete input;
		delete output;
		return 0;
	}

**Comment by atsushieno** [comment]
I forgot to mention: I rather assume that it is NOT rtmidi-specific issue. I am experiencing similar issue with portmidi (not with repro here; I'm using my .NET binding and seeing the issue), so it is more likely upstream.

**Comment by aib** [comment]
Is this simply that if you want to connect to an output port, an input port is automatically created and therefore listed among other input ports (and vice versa)?

**Comment by garyscavone** [comment]
Not clear this is a bug or not.
