### ISSUE TITLE
CoreMIDI: rtmidi believes virtual midi port open after it has been closed 

### ISSUE THREAD

**Issue by bmmund** [thestk/rtmidi#74]
When trying to open a virtual port after having closed a virtual port rtmidi spits out an error saying:

> MidiOutCore::openVirtualPort: a virtual output port already exists!

I believe this is because MIDIEndpointDispose is not cleaning out data->endpoint in the closePort code:

```
void MidiOutCore :: closePort( void )
{
  CoreMidiData *data = static_cast<CoreMidiData *> (apiData_);

  if ( data->endpoint ) {
    MIDIEndpointDispose( data->endpoint );
  }

  if ( data->port ) {
    MIDIPortDispose( data->port );
  }

  connected_ = false;
}
```

Perhaps I am missing something?

**Comment by SpotlightKid** [comment]
Closing a virtual port does not work on any RtMidi backend APi I have tested. You have to delete the RtMidiIn/out instance and make a new one to open a new virtual port.
