### ISSUE TITLE
Virtual port connection status

### ISSUE THREAD

**Issue by bmmund** [thestk/rtmidi#75]
I noticed that there is an isPortOpen() function which relays the connected_ bool but as the code stand this appears to only provide connection status for non-virtual ports. Is this intentional or should isPortOpen() return the connection status of a virtual port?

**Comment by garyscavone** [comment]
You are correct about the connected_ bool not being set for virtual ports. The reasoning is that the “openVirtualPort()” functions do not necessarily establish a link between RtMidi and a client but rather just create a mechanism through which such a link can happen. The clients that do establish such links then need to keep track that the virtual port remains valid.

I’m not doing a lot of MIDI programming these days so feel free to suggest changes if necessary (even just in the documentation).
