### ISSUE TITLE
I have problems when instantiating RtMidiIn object.

### ISSUE THREAD

**Issue by Boudibou** [thestk/rtmidi#76]
My problem is kind of similar to this:
https://github.com/thestk/rtmidi/issues/31

I am using Qt to compile RtMidi and my os is windows 8.1. I was trying to build a MidiReceiver class that would be communicating with MidiAnalyzer class and I noticed this:

`    std::cout<<"begin receiver init" << mAnalyzer->getName() << std::endl;
    midiIn = new RtMidiIn();
    std::cout<<"begin receiver init" << mAnalyzer->getName() << std::endl;
    midiOut = new RtMidiOut();
    std::vector<unsigned char> message;`

this code crashes (it crashes everytime I try to access to mAnalyzer (which is and instance of my other class MidiReceiver)

Also, this crashes too (like the other link):
`    std::cout<<"begin receiver init" << mAnalyzer->getName() << std::endl;
    midiOut = new RtMidiOut();
    midiIn = new RtMidiIn();
    std::vector<unsigned char> message;`

but this doesn't (as long as I don't try to access mAnalyzer):

    std::cout<<"begin receiver init" << mAnalyzer->getName() << std::endl;
    midiIn = new RtMidiIn();
    midiOut = new RtMidiOut();
    
    std::vector<unsigned char> message;

This is MidiReceiver.h: 

class MidiReceiver {
private:
    RtMidiOut *midiOut;
    RtMidiIn *midiIn;
    MidiAnalyzer *mAnalyzer;
    int name = 2;

public:
    MidiReceiver();
    void init();
    static void mycallback(double deltatime, std::vector< unsigned char > *message, void *userData);
    void publicCallback(std::vector< unsigned char > *message,double deltatime);
};

#endif // MIDIRECEIVER_H

It crashes in init function which sets up callback etc...
It is very strange it seems that calling "new RtMidiIn()" destroys everything in my class...

Thanks in advance for the help!

PS: I'm sorry I couldn't figure out the "insert code" button

**Comment by radarsat1** [comment]
Please post a complete crashing code example.  I can't see in your code where you initialize `mAnalyzer`.  Your title says it crashes when you instantiate RtMidiIn, but your message says that it crashes when accessing mAnalyzer.  Which is it?

**Comment by Boudibou** [comment]
I am sorry I have found a workaround since yesterday so I don't have the crashing code anymore. I am now instantiating RtMidiIn object directly in mAnalyzer (I removed MidiReceiver class). 
I am sorry also if I wasn't clear enough. This was the pb : 
//mAnalyzer was an associated object in my MidiReceiver.
std::cout<<"begin receiver init" << mAnalyzer->getName() << std::endl; 
//First call correctly print the name of mAnalyzer (string property). Then I call new RtMidiIn()
midiIn = new RtMidiIn(); 
//And the crash is next line when I try to access mAnalyzer it seems that the reference has been corrupted.
std::cout<<"begin receiver init" << mAnalyzer->getName() << std::endl;

Also, I noticed it crashed when I called "midiOut = new RtMidiOut()" before calling "midiIn = new RtMidiIn()" so it feels kind of like calling new RtMidiIn() destroyed every other attributes in my class.

Thanks anyways!

**Comment by radarsat1** [comment]
I think it's a bit too ambiguous to consider it a bug.  If you feel like hunting it down and coming up with a more concrete example, feel free to re-open ;)  I think it might just be a problem in your code however, that you seem to have a fixed.
