### ISSUE TITLE
Windows: setting filters creates wrong timestamps

### ISSUE THREAD

**Issue by emem67** [thestk/rtmidi#82]
Hi
In the Windows version the midi in event time stamp is calculated for all the coming events, including the event filtered.
Supposing you use ignoreTypes to get rid of active sense. The event time stamp is calculated anyway and the next event timestamp will be calculated from the active sense and not from the last non-filtered event.
This make the timestamp wrong since it may refers to events filtered out.

This can be fixed moving the line of code
apiData->lastTime = timestamp;

```
  else apiData->message.timeStamp = (double) ( timestamp - apiData->lastTime ) * 0.001;
  // Remove this
  //apiData->lastTime = timestamp;

  if ( inputStatus == MIM_DATA ) { // Channel or system message
```

after the filters (line 2012)
just before the line related firing the callback

```
    else return;
  }

  // Moved here!
  apiData->lastTime = timestamp;

  if ( data->usingCallback ) {
    RtMidiIn::RtMidiCallback callback = (RtMidiIn::RtMidiCallback) data->userCallback;
```

In this way filtered events are not calculated and the deltatime is related to the unfiltered events
regards

**Comment by garyscavone** [comment]
This should be submitted as a pull request.

**Comment by emem67** [comment]
Well, this was one year ago, at that time I was not understanding git.
It was an attempt to give an hand, I will see what I can do.

**Comment by radarsat1** [comment]
Hopefully patched in 67804750a5aa9034d578b8073f29eb4dffd4f333, needs testing.

**Comment by radarsat1** [comment]
I reviewed the other backends and also submitted a similar fix for OS X.  It seems the design of the ALSA backend does not allow for this problem, and the JACK backend does not seem to implement filtering.

**Comment by radarsat1** [comment]
Hoping this is fixed as per my post here from last year, closing.
