### ISSUE TITLE
Warning C4996 'strdup': The POSIX name for this item is deprecated (VS2015)

### ISSUE THREAD

**Issue by Patrik356b** [thestk/rtmidi#83]
`Warning	C4996 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details rtmidilib	c:\dev\rtmidi-master\rtmidi_c.cpp line:70`

This may or may not be a problem. Microsoft is very fuzzy about the actual meaning of "deprecated".

**Comment by radarsat1** [comment]
I think, like almost every C++ project in the world, we will chose to ignore this warning from Microsoft.

**Comment by Patrik356b** [comment]
Okay

**Comment by garyscavone** [comment]
Feel free to submit a PR to fix it.

**Comment by Nytra** [comment]
https://github.com/thestk/rtmidi/pull/361
