### ISSUE TITLE
Assert error with Midi Output

### ISSUE THREAD

**Issue by Patrik356b** [thestk/rtmidi#86]
As there isn't much information for a rusty C++ developer to use, i run into odd issues like this one...

First error happens during runtime, second happens only if i click "Continue".
Retry/Ignore leads to a "Application is not responding" message on Windows.

Screenshot: [rtmidi-assert](https://cloud.githubusercontent.com/assets/2000703/18227946/3b0219d6-7237-11e6-8a14-384e1d194158.png)

This code is based on the [MIDI Output](http://www.music.mcgill.ca/~gary/rtmidi/index.html#output) sample code

```
int main()
{
	std::cout << "\n Application started\n";

	// MIDI
	RtMidiOut *midiout = 0;
	int MidiOUT;

	// RtMidiOut constructor
	try {
		midiout = new RtMidiOut();
	}
	catch (RtMidiError &error) {
		error.printMessage();
		exit(EXIT_FAILURE);
	}

	// Check outputs.
	nPorts = midiout->getPortCount();
	std::cout << "\nThere are " << nPorts << " MIDI output ports available.\n";
	for (unsigned int i = 0; i<nPorts; i++) {
		try {
			portName = midiout->getPortName(i);

			portName = midiout->getPortName(i);
			if (portName.find("Launchkey Mini") != std::string::npos)
			{
				MidiOUT = i;
			}
		}
		catch (RtMidiError &error) {
			error.printMessage();
		}
		std::cout << "  Output Port #" << i + 1 << ": " << portName << '\n';
	}
	std::cout << '\n';

	midiout->openPort(MidiOUT);

	// assert happens somewhere below
	std::vector<unsigned char> message; // To be used later
										// try a led
	message[0] = 153;
	message[1] = 40;
	message[2] = 54;
	midiout->sendMessage(&message);
```

**Comment by DouglasHeriot** [comment]
This is actually nothing to do with RtMidi. The error says "Expression: vector subscript out of range" – it means when you do `message[0]`, there is no element 0. The vector is constructed empty.

Have a good through the C++ documentation. Whenever I use any std classes, I make sure I read exactly what everything does. In this case, it notes “Unlike std::map::operator[], this operator never inserts a new element into the container”
http://en.cppreference.com/w/cpp/container/vector/operator_at

And after you get an assertion, if you continue execution by ignoring or retrying, it’s hard to make any assumptions about the state of anything anymore – so I don’t even bother. Just try to reproduce again and step through in debugger as it first happens.

**Comment by Patrik356b** [comment]
The error comes from your sample code, so there wasn't much I could do at
the moment. I will have a look at the link tho.

**Comment by garyscavone** [comment]
On Sep 4, 2016, at 6:56 AM, TheExileFox <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> The error comes from your sample code, so there wasn't much I could do at
> the moment. I will have a look at the link tho.

That is not true.  If you look at the sample code, you will see 3 push_back() function calls, which cause the std::vector class to allocate space.  In your example, you omitted those calls.  Please understand what the example code does before you start modifying and cutting pieces of it out.

**Comment by Patrik356b** [comment]
It wasn't clear to me what it did due to the usage. It's confusing with Embedded Pawn as my background.
