### ISSUE TITLE
No port names on ALSA

### ISSUE THREAD

**Issue by aib** [thestk/rtmidi#88]
On ALSA (asound), port names returned are of the form `<client name> <client id>:<port id>`. The cid:pid pair is unique, but this makes it hard to look for ports by name. Mentioned in #54, but I thought it would be better to move the discussion here.

**Comment by aib** [comment]
Using these samples:

```
RtMidiOut midiOut;
midiOut.openVirtualPort("Testing123");
```
```
RtMidiIn midiIn;
for (unsigned int i=0; i<midiIn.getPortCount(); ++i) {
    std::cout << midiIn.getPortName(i) << std::endl;
}
```

I get,
on Jack: `RtMidi Output Client:Testing123`
on ALSA: `RtMidi Output Client 129:0`

**Comment by jk-5** [comment]
Can confirm that the names on OSX are the same names as entered when creating the virtual device. Looks like it's only an alsa issue

**Comment by radarsat1** [comment]
Just tested on ALSA and it seems for me that midiprobe is able to detect the virtual port opened in another process without issues.  Assuming fixed.
