### ISSUE TITLE
Error in "sendMessage()" while sending SysEx messages longer than 258 bytes on MacOSX

### ISSUE THREAD

**Issue by sanotronics** [thestk/rtmidi#91]
Hello!

I have a self-made cross-platform app, developed with Python 3.4, and I use rtmidi to send SysEx messages to configure an Arduino UNO.

The configuration message has a dinamic size up to 1024 bytes.

On windows and linux, everything works like a charm, but on MacOSx (tried with El Capitan) I get an error every time I try to send a message longer than 258 bytes (It's tricky to know if this is the actual limit, but it won't send 260 bytes, so it's either 258 or 259).

The error is "MidiOutCore::sendMessage: could not allocate packet list", which I found to be set by a null pointer to a packet on line 1049 of [RtMidi.cpp](https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp).

From what I can see around those lines of code, the pointer is set by CoreMIDI's method MIDIPacketListAdd(). And in the [documentation](https://developer.apple.com/reference/coremidi/1495128-midipacketlistadd) reads:
_"**Returns null if there was not room in the packet for the event**; otherwise returns a packet pointer which should be passed as curPacket in a subsequent call to this function."_

If further info is needed, I'll be around.

**Comment by radarsat1** [comment]
RtMidi is correctly relaying an error from the operating system.  But I don't know why it would fail on messages only ~250 bytes long, maybe MIDISendSysex() would work better?  It seems there is a [comment](https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L1048) saying that MIDISendSysex is used, but it's not found in the code,

**Comment by garyscavone** [comment]
I did a quick test with the sysextest.cpp program, sending messages > 250 bytes, and I didn't experience any problems (OS-X 10.12.6 Sierra). So, I'm closing this. We can reopen it if someone can verify the reported behaviour.
