### ISSUE TITLE
Map between Linux USB id and RtMidi port name?

### ISSUE THREAD

**Issue by snhirsch** [thestk/rtmidi#96]
This is turning out not to be so simple.  I am trying to write a udev rule to start an rtmidi based application when a specific USB vender + device id is seen in a hot-plug event.  The only place I've found where ALSA bridges between the two domains is the /proc/asound/<device>/usbid file.  So, in theory it's possible to exhaustively check all usbid files on hot-plug until I find the match.  However, that doesn't get me to any reliable way of determining the ALSA port name required by rtmidi itself.  This naming convention seems to change depending on the version of RtMidi in use and I've found no way to synthesize it from data under /proc/asound.  Am I missing something obvious?  Can anyone suggest a way to easily determine the RtMidi port name from the USB device id?

**Comment by SpotlightKid** [comment]
See also #89.

**Comment by garyscavone** [comment]
Closing ... another issue regarding port names that may or may not be solvable uniformly across all supported apis.
