### ISSUE TITLE
RtMidi compilation error on OS X

### ISSUE THREAD

**Issue by ambidextrousTx** [thestk/rtmidi#97]
I am working through the [Seven More Languages in Seven Weeks](https://pragprog.com/book/7lang/seven-more-languages-in-seven-weeks) book. The Lua chapter has some interfacing code between Lua and C++, and they use RTMidi for the example.

I am getting the following error. I have Lua and RtMidi both installed through Homebrew. I am running macOS Sierra on a late 2016 Macbook Pro. Any help would be appreciated. Thanks!

```
$ make
Scanning dependencies of target play
[ 50%] Building CXX object CMakeFiles/play.dir/play.cpp.o
[100%] Linking CXX executable play
Undefined symbols for architecture x86_64:
  "RtMidiOut::RtMidiOut(RtMidi::Api, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1
:allocator<char> >)", referenced from:
      ___cxx_global_var_init in play.cpp.o
  "RtMidiOut::~RtMidiOut()", referenced from:
      ___cxx_global_var_init in play.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [play] Error 1
make[1]: *** [CMakeFiles/play.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by radarsat1** [comment]
It appears you are maybe compiling with an RtMidi.h that does not correspond with the librtmidi.so library you are linking against.  Something like that.

I got the code to compile and link, but had to modify the CMakeLists.txt which comes with the source code. It is not a verify sophisticated CMakeLists.txt.  Here is the one I used, with liblua5.3-dev and librtmidi-dev installed on my Ubuntu Xenial machine:

~~~
cmake_minimum_required (VERSION 2.8)
project (play)
add_executable (play play.cpp)

find_library(RTMIDI rtmidi REQUIRED)
find_library(LUA lua5.3 REQUIRED)

target_link_libraries (play ${LUA} ${RTMIDI})

include_directories(/usr/include/lua5.3)
~~~

The output I get is,

~~~
$ make
Scanning dependencies of target play
[ 50%] Building CXX object CMakeFiles/play.dir/play.cpp.o
[100%] Linking CXX executable play
[100%] Built target play
~~~

Hope this helps.

**Comment by ambidextrousTx** [comment]
@radarsat1 Thanks. I am on OS X. I added the `find_library` statements like you did, and used `lua`, not `lua5.3` - I was able to compile and run the example as well.

**Comment by radarsat1** [comment]
Great!
